# SPDX-License-Identifier: Apache-2.0
---

# This file does not currently have dedicated validation tasks for ABAP,
# because they are primarily part of kernel validation.

- name: SAP Patching - Validation - ABAP - Set fact that validation was completed
  ansible.builtin.set_fact:
    __sap_patching_fact_validations_completed:
      "{{ __sap_patching_fact_validations_completed | d([]) + [validation_item] }}"
