---
# Validates all mandatory variables
# Task dependand variables are validated in their respective validation files (e.g. hdb_server.yml, hdb_client.yml, host_agent.yml)

- name: Assert that the variable 'sap_patching_execution_plan' is defined and valid
  ansible.builtin.assert:
    that:
      - sap_patching_execution_plan is defined
      - sap_patching_execution_plan is iterable
      - sap_patching_execution_plan | length > 0
    fail_msg: |
      The variable 'sap_patching_execution_plan' is undefined, empty, or invalid.
      It should be a list of tasks to execute.

- name: Assert that *to_apply variables are valid
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.vars', item, default='SAP_PATCHING_UNDEFINED_VARIABLE_DETECTED') != 'SAP_PATCHING_UNDEFINED_VARIABLE_DETECTED'
      - lookup('ansible.builtin.vars', item) is string
      - lookup('ansible.builtin.vars', item) | trim | length > 0
    fail_msg: |
      {% if lookup('ansible.builtin.vars', item, default='SAP_PATCHING_UNDEFINED_VARIABLE_DETECTED') == 'SAP_PATCHING_UNDEFINED_VARIABLE_DETECTED' %}
        The variable '{{ item }}' is undefined.
      {% elif lookup('ansible.builtin.vars', item) is not string %}
        The variable '{{ item }}' is not a String.
      {% else %}
        The variable '{{ item }}' is empty.
      {% endif %}
      It should be the name of the symbolic link pointing to the kernel folder to be used by the patching process.
  loop:
    - sap_patching_kernel_to_apply_symlink
    - sap_patching_hdb_client_to_apply_symlink
    - sap_patching_hdb_server_to_apply_symlink
    - sap_patching_host_agent_to_apply_symlink
    - sap_patching_webdisp_to_apply_symlink
