# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Patching - Validation - Prepare - Assert that the variable 'sap_patching_file_owner' is defined and valid
  ansible.builtin.assert:
    that:
      - sap_patching_file_owner is defined
      - sap_patching_file_owner is string
      - sap_patching_file_owner | length > 0
    fail_msg: |
      The variable 'sap_patching_file_owner' is undefined, empty, or invalid.
      It should be a string containing a valid user.

# Ensure that user is present before we attempt become
- name: SAP Patching - Validation - Prepare - Assert that the variable 'sap_patching_file_owner' contains valid user
  ansible.builtin.assert:
    that:
      - ansible_facts["getent_passwd"][sap_patching_file_owner] is defined
    fail_msg: |
      FAIL: The variable 'sap_patching_file_owner' must be set to a valid user on the system.
      The current value '{{ sap_patching_file_owner }}' does not correspond to any user on the system.


- name: SAP Patching - Validation - Prepare - Assert that the variable 'sap_patching_file_group' is defined and valid
  ansible.builtin.assert:
    that:
      - sap_patching_file_group is defined
      - sap_patching_file_group is string
      - sap_patching_file_group | length > 0
    fail_msg: |
      The variable 'sap_patching_file_group' is undefined, empty, or invalid.
      It should be a string containing a valid group.

# Ensure that group is present before we attempt become
- name: SAP Patching - Validation - Prepare - Assert that the variable 'sap_patching_file_group' contains valid group
  ansible.builtin.assert:
    that:
      - ansible_facts["getent_group"][sap_patching_file_group] is defined
    fail_msg: |
      FAIL: The variable 'sap_patching_file_group' must be set to a valid group on the system.
      The current value '{{ sap_patching_file_group }}' does not correspond to any group on the system.


- name: SAP Patching - Validation - Prepare - Assert that the variable 'sap_patching_sapcar_path' is defined and valid
  ansible.builtin.assert:
    that:
      - sap_patching_sapcar_path is defined
      - sap_patching_sapcar_path is string
      - sap_patching_sapcar_path | length > 0
    fail_msg: |
      The variable 'sap_patching_sapcar_path' is undefined, empty, or invalid.
      It should be a string containing a valid file path.

- name: SAP Patching - Validation - Prepare - Check if path in the variable 'sap_patching_sapcar_path' exists and is a directory
  ansible.builtin.stat:
    path: "{{ sap_patching_sapcar_path }}"
  register: __sap_patching_register_sapcar_path_stat
  failed_when:
    - not (__sap_patching_register_sapcar_path_stat.stat.exists
        and __sap_patching_register_sapcar_path_stat.stat.isdir)


- name: SAP Patching - Validation - Prepare - Assert that the variable 'sap_patching_sapcar_file_name' is defined and valid
  ansible.builtin.assert:
    that:
      - sap_patching_sapcar_file_name is defined
      - sap_patching_sapcar_file_name is string
      - sap_patching_sapcar_file_name | length > 0
    fail_msg: |
      The variable 'sap_patching_sapcar_file_name' is undefined, empty, or invalid.
      It should be a string containing a valid file name.

- name: SAP Patching - Kernel - Prepare - Check if file in the variable 'sap_patching_sapcar_file_name' exists
  ansible.builtin.stat:
    path: "{{ __sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}"
  register: __sap_patching_register_sapcar_file_name_stat
  failed_when: not __sap_patching_register_sapcar_file_name_stat.stat.exists


- name: SAP Patching - Validation - Prepare - Set fact that validation was completed
  ansible.builtin.set_fact:
    __sap_patching_fact_validations_completed:
      "{{ __sap_patching_fact_validations_completed | d([]) + [validation_item] }}"
