---
# WARNING: NOT TESTED ON SuSE yet!
- name: Relocate '{{ sap_patching_hdb_server_clu_hdb_resource_name }}'
  run_once: true
  ansible.builtin.command: crm --force resource move {{ sap_patching_hdb_server_clu_hdb_resource_name }} --autodelete
  become: true
  register: __sap_patching_register_hdb_clu_relocate_output
  changed_when: "'resource ''' ~ sap_patching_hdb_server_clu_hdb_resource_name ~ ''' is master on node' in __sap_patching_register_hdb_clu_relocate_output.stdout or __sap_patching_register_hdb_clu_relocate_output.rc == 0"
  failed_when: "'failed' in __sap_patching_register_hdb_clu_relocate_output.stderr or __sap_patching_register_hdb_clu_relocate_output.rc != 0"
