---
- name: Set cluster maintenance mode to '{{ __hdb_server_cluster_maintenance_op }}'
  run_once: true
  ansible.builtin.command: pcs property set maintenance-mode={{ __hdb_server_cluster_maintenance_op }}
  become: true
  register: __sap_patching_register_hdb_clu_maintenance_output
  changed_when: __sap_patching_register_hdb_clu_maintenance_output.rc == 0
  failed_when: "'failed' in __sap_patching_register_hdb_clu_maintenance_output.stderr or __sap_patching_register_hdb_clu_maintenance_output.rc != 0"
