---
# # sapstartsrv must be present on each working system, we are looking for ASCS*, D* or ERS* folders
# - name: Get all instances on the current host based on the file system
#   ansible.builtin.shell: |
#     ls -d /usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/[AED]*/exe/sapstartsrv | awk -F '/' '{print $5}'
#   register: __sap_patching_register_sap_instances
#   changed_when: false
#   failed_when: __sap_patching_register_sap_instances.rc != 0

# TODO: Consider using lssap instead? That will show all not just running sapstartsrv instances
# /usr/sap/hostctrl/exe/lssap | grep {{ __sap_patching_fact_sap_system_sid | upper }} | awk -F '|' '{print $2}'
# Also ignoring SUM and HDB sapstartsrv processes
- name: Get all running instances of sapstartsrv on the current host based on the running sapstartsrv processes
  ansible.builtin.shell: |
    set -o pipefail && ps -U {{ __sap_patching_fact_sap_system_sid | lower }}adm -o cmd --no-header | grep sapstartsrv | grep -v SUM | grep -v HDB | grep -v grep | awk -F '/' '{print $5}'
  register: __sap_patching_register_sap_instances
  changed_when: false
  failed_when: __sap_patching_register_sap_instances.rc != 0

# The instance list should contain W, D, ASCS or ERS
- name: Parse instance types and numbers from __sap_patching_register_sap_instances output
  ansible.builtin.set_fact:
    __sap_patching_fact_instance_list: "{{ __sap_patching_register_sap_instances.stdout_lines | map('regex_search', '([A-Z]+)([0-9]{2})', '\\1', '\\2') }}"
    __sap_patching_fact_instance_dict: "{{ __sap_patching_fact_instance_list | community.general.dict }}"
