---
- name: Run this on specific server
  delegate_to: "{{ _sap_patching_delegated_to_host }}"
  #delegate_facts: true
  block:
    - name: Site info
      when:
        - "'mode=none' not in _sap_patching_hdb_hsr_srstate.stdout"
      ansible.builtin.debug:
        msg:
          - "Processing HANA DB server '{{ _sap_patching_hdb_hsr_site_to_host[_sap_patching_hdb_hsr_site[0]] }}' on site '{{ _sap_patching_hdb_hsr_site[0] }}'"

    # - name: Debug hosts
    #   ansible.builtin.debug:
    #     msg:
    #       - "Inventory hostname: {{ inventory_hostname }}"
    #       - "Inventory hostname short: {{ inventory_hostname_short }}"
    #       - "Ansible hostname: {{ ansible_hostname }}"
    #       - "Delegated to: {{ _sap_patching_delegated_to_host }}"

    - name: Set hdblcm action parameter based on update_mode
      ansible.builtin.set_fact:
        sap_patching_hdb_server_hdblcm_action: >-
          {% if sap_patching_params.update_mode == 'prepare' %}
          --action=update --prepare_update
          {% else %}
          --action=update
          {% endif %}
    # {% elif sap_patching_params.update_mode == 'resume' %}
    # --action=update --resume_update

    # If clustered and not in prepare mode then put cluster in maintenance mode
    # 'false/true' are strings, not booleans
    - name: Set cluster maintenance mode ON (if clustered)
      run_once: true
      vars:
        __hdb_server_cluster_maintenance_op: 'true'
      ansible.builtin.include_tasks:
        file: "{{ ansible_facts['os_family'] }}/cluster_maintenance.yml"
      when:
        - sap_patching_hdb_server_is_clustered | bool
        - sap_patching_params.update_mode != 'prepare'

    - name: Include hdblcm config file template
      ansible.builtin.include_tasks: hdblcm_configfile.yml
    #_sap_patching_hdb_hdblcm_configfile

    # Execute update using hdblcm
    - name: Update HANA DB server
      ansible.builtin.command: >-
        '{{ sap_patching_hdb_server_to_apply }}/hdblcm' {{ sap_patching_hdb_server_hdblcm_action }}
        -s {{ sap_patching_hdb_system_sid }} --batch
        {{ '--system_user=' + sap_patching_hdb_server_cf_system_user if sap_patching_hdb_server_cf_system_user | d('', true) | length > 0 else '' }}
        --configfile={{ _sap_patching_hdb_hdblcm_configfile }}
      register: sap_patching_hdb_server_hdblcm_output
      # args:
      #   chdir: '"{{ sap_patching_hdb_server_to_apply }}"'
      become: true
      changed_when: "('SAP HANA Database components updated' in sap_patching_hdb_server_hdblcm_output.stdout or 'Update of SAP HANA Database components prepared' in sap_patching_hdb_server_hdblcm_output.stdout) and sap_patching_hdb_server_hdblcm_output.rc == 0"
      failed_when: "'failed' in sap_patching_hdb_server_hdblcm_output.stderr or sap_patching_hdb_server_hdblcm_output.rc != 0"

    # We are inside the HSR loop, but the primary/master site may have switched if we are in a cluster and patching the primary/secondary pair
    # So we need to re-check the HSR status and make sure we know who is the current primary
    # We use run_once "trick" here to set this variable on all hosts in the play.
    - name: Block to refresh HSR information
      run_once: true
      when:
        - sap_patching_params.update_mode != 'prepare'
        - "'mode=none' not in _sap_patching_hdb_hsr_srstate.stdout"
      block:
        - name: "SAP HSR - Check System Replication Status - again"
          ansible.builtin.shell: |
            source /usr/sap/{{ sap_patching_hdb_system_sid }}/home/.sapenv.sh && \
            {{ sap_patching_hdb_server_install_path }}/hdbnsutil \
            -sr_state -sapcontrol=1
          become: true
          become_user: "{{ sap_patching_hdb_system_sid | lower }}adm"
          register: _sap_patching_hdb_hsr_srstate2
          changed_when: false
          failed_when: "'SAPCONTROL-OK' not in _sap_patching_hdb_hsr_srstate2.stdout or _sap_patching_hdb_hsr_srstate2.rc != 0"

        - name: HSR is enabled  - again
          when: "'mode=none' not in _sap_patching_hdb_hsr_srstate2.stdout"
          block:
            - name: Make sure the system is online before proceeding  - again
              ansible.builtin.assert:
                that:
                  - "'online=true' in _sap_patching_hdb_hsr_srstate2.stdout"
                fail_msg: "System offline, cannot proceed with patching."
                success_msg: "System is online, proceeding ..."
              changed_when: false

            - name: Extract and sort siteTier entries from HSR state output - again
              ansible.builtin.set_fact:
                _sap_patching_hdb_hsr_sites2: >-
                  {{
                    _sap_patching_hdb_hsr_srstate2.stdout_lines
                    | select('match', '^siteTier/')
                    | map('regex_search', '^siteTier/(.+)=(.+)$', '\1','\2')
                    | sort(attribute=1, reverse=true)
                  }}

            - name: Set site to host dictionary - again
              ansible.builtin.set_fact:
                _sap_patching_hdb_hsr_site_to_host2: >-
                  {{
                    _sap_patching_hdb_hsr_srstate2.stdout_lines
                    | select('match', '^mapping/')
                    | map('regex_search', '^mapping/.+=(.+)/(.+)$', '\1','\2')
                    | community.general.dict
                  }}

            # This needs to be done on the master site. The lowest tier site is the master and it should be up.
            # If it is in the current inventory then we can do this check. If we can't we'll fall back to hdbscons below.
            # Loop 30 times with 20 second delay until replication is active or we get confirmation that this is not the master site.

            ## If HSR is enabled check the replication is active
            # You can check that the REPLICATION_STATUS column in M_SERVICE_REPLICATION has the value ACTIVE for all services.
            # try first: HDBSettings.sh systemReplicationStatus.py but this needs to be run on master
            # HDBSettings.sh systemReplicationStatus.py |awk -F '|' '/^this system/ { print }  $9 ~ /hdbserver02\s+/ { print  $3, $5, $8, $9, $15, $17}'
            # Host          Site Name  Secondary     Replication  Secondary
            #                          Host          Status       Fully Synced
            # ------------  ---------  ------------  -----------  ------------
            # hdbserver01  nameserver    DCW01      hdbserver02  ACTIVE               True
            # hdbserver01  xsengine      DCW01      hdbserver02  ERROR               False
            # hdbserver01  docstore      DCW01      hdbserver02  ERROR               False
            # hdbserver01  indexserver   DCW01      hdbserver02  ERROR               False
            # hdbserver01  dpserver      DCW01      hdbserver02  ERROR               False
            #
            # this system is not a system replication site
            #
            # this system is either not running or not primary system replication site
            #
                #   source ~/.profile && HDBSettings.sh systemReplicationStatus.py | \
                # awk -F '|' '/^this system/ {print} $9 ~ /{{ hostvars[inventory_hostname]['ansible_hostname'] }}/ {print $17}'
                #_sap_patching_hdb_hsr_site_to_host[_sap_patching_hdb_hsr_site[0]] == _sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first ]]
            - name: Check HSR replication state of replication target (using Python script) on master site
              delegate_to: "{{ _sap_patching_hdb_host_fqdn[_sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first]] }}"
              when:
                - "'mode=none' not in _sap_patching_hdb_hsr_srstate2.stdout"
                - _sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first] in ansible_play_hosts | map('split', '.') | map('first') | list
                - _sap_patching_hdb_hsr_site_to_host[_sap_patching_hdb_hsr_site[0]] != _sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first ]
              ansible.builtin.shell: |
                set -o pipefail && source ~/.profile && HDBSettings.sh systemReplicationStatus.py | \
                awk -F '|' '/^this system/ {print} $9 ~ /{{ _sap_patching_hdb_hsr_site_to_host[_sap_patching_hdb_hsr_site[0]] }}/ {print $17}'
              args:
                executable: /bin/bash
              register: _sap_patching_hdb_hsr_srstatus_target
              become: true
              become_user: "{{ sap_patching_hdb_system_sid | lower }}adm"
              until: "'False' not in _sap_patching_hdb_hsr_srstatus_target.stdout or 'this system' in _sap_patching_hdb_hsr_srstatus_target.stdout"
              retries: 30
              delay: 20
              changed_when: false

            - name: Check HSR replication state of replication master (using Python script) on master site
              delegate_to: "{{ _sap_patching_hdb_host_fqdn[_sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first]] }}"
              when:
                - "'mode=none' not in _sap_patching_hdb_hsr_srstate2.stdout"
                - _sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first] in ansible_play_hosts | map('split', '.') | map('first') | list
                - _sap_patching_hdb_hsr_site_to_host[_sap_patching_hdb_hsr_site[0]] == _sap_patching_hdb_hsr_site_to_host2[_sap_patching_hdb_hsr_sites2 | last | first ]
              ansible.builtin.shell: |
                set -o pipefail && source ~/.profile && HDBSettings.sh systemReplicationStatus.py | \
                awk -F '|' '/^this system/ {print} $3 ~ /{{ _sap_patching_hdb_hsr_site_to_host[_sap_patching_hdb_hsr_site[0]] }}/ {print $17}'
              args:
                executable: /bin/bash
              register: _sap_patching_hdb_hsr_srstatus_master
              become: true
              become_user: "{{ sap_patching_hdb_system_sid | lower }}adm"
              until: "'False' not in _sap_patching_hdb_hsr_srstatus_master.stdout or 'this system' in _sap_patching_hdb_hsr_srstatus_master.stdout"
              retries: 30
              delay: 20
              changed_when: false

            # <sid>adm@hdbserver01:/usr/sap/<SID>/HDB00> hdbcons "replication info"| grep ReplicationStatus_ | awk -F ':' '{print $2}' | sed -n 's/.*ReplicationStatus_\(.*\)/\1/p'
            # Error
            # Active
            # Syncing
            # If we couldn't get HSR status above (typically because master site is not in the current inventory) we try hdbcons instead.
            # This is less reliable as the step above if the system is both source and target of replication i.e. in a middle of the chain
            # Loop 30 times with 20 second delay until replication is active
            - name: Check HSR replication state (using hdbcons) on the current site
              when:
                - "'mode=none' not in _sap_patching_hdb_hsr_srstate.stdout"
                - "_sap_patching_hdb_hsr_srstatus_target.stdout | d('',true) | length == 0 or 'this system' in _sap_patching_hdb_hsr_srstatus_target.stdout"
                - "_sap_patching_hdb_hsr_srstatus_master.stdout | d('',true) | length == 0 or 'this system' in _sap_patching_hdb_hsr_srstatus_master.stdout"
              ansible.builtin.shell: |
                set -o pipefail && source ~/.profile && hdbcons "replication info"| grep ReplicationStatus_ | awk -F ':' '{print $2}' | sed -n 's/.*ReplicationStatus_\(.*\)/\1/p'
              args:
                executable: /bin/bash
              register: _sap_patching_hdb_hsr_srstatus_hdbcons
              become: true
              become_user: "{{ sap_patching_hdb_system_sid | lower }}adm"
              until: "'Error' not in _sap_patching_hdb_hsr_srstatus_hdbcons.stdout or 'Syncing' not in _sap_patching_hdb_hsr_srstatus_hdbcons.stdout"
              retries: 30
              delay: 20
              changed_when: false
              failed_when: _sap_patching_hdb_hsr_srstatus_hdbcons.stdout | length == 0

    # If clustered and not in prepare mode then turn off cluster maintenance mode
    # 'false/true' are strings, not booleans
    - name: "Set cluster maintenance mode OFF (if clustered)"
      run_once: true
      vars:
        __hdb_server_cluster_maintenance_op: 'false'
      ansible.builtin.include_tasks:
        file: "{{ ansible_facts['os_family'] }}/cluster_maintenance.yml"
      when:
        - sap_patching_hdb_server_is_clustered | bool
        - sap_patching_params.update_mode != 'prepare'

    # TODO: Ideally we check that the resource is fully running before trying to relocate it, but issue is with
    # doing it reliably across RHEL/SLES and when cluster hasn't been created using SAP LL roles.
    # see community.general.pacemaker_info
    # So for now we wait for 1 minute to allow the resource to stabilise (it shouldn't need much as we only turned off the maintenance mode).
    - name: Wait 60 seconds for HANADB clone resource to stabilise (if clustered)
      ansible.builtin.wait_for:
        timeout: 60
      when:
        - sap_patching_hdb_server_is_clustered | bool
        - sap_patching_params.update_mode != 'prepare'

    # if cluster is on, initiate switchover after patching
    # check that it hasn't been done already
    - name: Relocate the HDB resource (if clustered)
      run_once: true
      ansible.builtin.include_tasks:
        file: "{{ ansible_facts['os_family'] }}/cluster_hdb_relocate.yml"
      when:
        - sap_patching_hdb_server_is_clustered | bool
        - sap_patching_params.update_mode != 'prepare'
        - not _sap_patching_hdb_cluster_relocated | d(false, true) | bool

    # We use run_once "trick" here to set this variable on all hosts in the play.
    # If this is the second iteration of main loop through HSR sites, it will read the correct value on all hosts.
    - name: Mark that relocation was already completed (if clustered)
      run_once: true
      ansible.builtin.set_fact:
        _sap_patching_hdb_cluster_relocated: true
      when:
        - sap_patching_hdb_server_is_clustered | bool
        - sap_patching_params.update_mode != 'prepare'
        - not _sap_patching_hdb_cluster_relocated | d(false, true) | bool
