---
# Obsolete, to be removed in future versions
# # Main entry for HANA DB client patching
# - name: Prepare HANA DB client
#   when: "'nwas_abap_pas' in group_names"
#   ansible.builtin.include_tasks:
#     file: hdb_client_prepare.yml
#     apply:
#       tags:
#         - sap_patching_hdb_client_prepare
#   tags:
#     - sap_patching_hdb_client_prepare

# # Application server must be down for this to be succesfull
# - name: Apply HANA DB client
#   when: "'nwas_abap_pas' in group_names or 'nwas_abap_aas' in group_names"
#   ansible.builtin.include_tasks:
#     file: hdb_client_apply.yml
#     apply:
#       tags:
#         - sap_patching_hdb_client_apply
#   tags:
#     - sap_patching_hdb_client_apply
