---
####################        General settings        ####################
# This drives what actions this role takes and in what order
sap_patching_execution_plan:

#### SAP system definitions ####
# SAP System SID
sap_patching_sap_system_sid:

# SAPCAR information
sap_patching_sapcar_path: "{{ nbs_software_base_path }}"
sap_patching_sapcar_file_name: SAPCAR.EXE

# User which owns all extracted files, typically <sid>adm or some kind of common shared user on NFS share
# If the prepare (extraction) is executed on the controller node and <sid>adm is not available, root can be used
sap_patching_file_owner: "{{ sap_patching_sap_system_sid | lower }}adm"
# Same as owner above, just for a group. Default is sapsys.
sap_patching_file_group: sapsys


####################    Kernel patching settings    ####################
# Base kernel directory where the kernel SP directories are created
sap_patching_kernel_base: /install/kernel
# Directory where the SAR files are located (used during the prepare step)
sap_patching_kernel_source: "{{ sap_patching_kernel_base }}/source"

# What kernel version are we extracting from SAR files - set to 'autodetect' to use disp+work to determine the extracted kernel version and patch number.
# If for some reason you don't want (or can't) use autodetection, set this a specific kernel version e.g. 793 (format is `<NNN>` where N is a number).
# The kernel patch will be determined from the name of the SAR files.
sap_patching_kernel_prepare_version: autodetect

# To be used when not patching dw or SAPEXE e.g. when adding extra patch like R3trans to existing kernel patch
# Format is <kernel_version>p<patch_number> e.g. 793p320
sap_patching_kernel_prepare_appendto_version:

# Either relative (to sap_patching_kernel_base) or absolute path to the kernel which will be applied
# If not set, sap_patching_kernel_to_apply_symlink will be used
# abap_kernel_prepare task will set this if it was executed and kernel was extracted
sap_patching_kernel_to_apply:

# If true, the kernel source SAR files are expected to be present on the local host (e.g. NFS share)
# If false, the kernel source SAR files will be copied from the Ansible controller to the target host
sap_patching_kernel_extracted_shared: true

# How is the ABAP system restarted after kernel patching
# Options are:  'all' - restart the whole system including SapStartService, 'rks' - restart using Rolling Kernel Switch (RKS), 'bootstrap' - restart only sapstartsrv and run sapcpe
sap_patching_kernel_restart_strategy: rks


####################   HDB client patching settings   ####################
# Base HDB client directory where the HDB client SAR file are stored and extraction directories are created
sap_patching_hdb_client_base: /install/hanadb/client
# Directory where the SAR files are located (used during the prepare step)
sap_patching_hdb_client_source: "{{ sap_patching_hdb_client_base }}/source"

# If using individual client installation - installation path of the HDB client (used for --path option of hdbinst)
# **mutually exclusive with sap_patching_hdb_client_shared_path**
sap_patching_hdb_client_install_path: "{{ '/usr/sap/' +  sap_patching_sap_system_sid | upper  + '/hdbclient' if not (sap_patching_hdb_client_shared_path | d('', true) | length > 0) }}"

# If using shared client installation - path to the shared directory  (used for --sapmnt option of hdbinst)
# **mutually exclusive with sap_patching_hdb_client_install_path**
sap_patching_hdb_client_shared_path:

# If true, the extracted HDB client source files are expected to be present on the local host (e.g. NFS share) following the execution of the prepare step.
# If false, the extracted HDB client source files will be copied from the Ansible controller to the target host
sap_patching_hdb_client_extracted_shared: true

# Where to store a local copy of extracted HDB client files as they must be present locally in order to run hdbinst
sap_patching_hdb_client_extracted_local_path: /install-local/hanadb/client


####################   HDB server patching settings   ####################
# HANA DB platform System SID
sap_patching_hdb_system_sid:

# Base HDB server directory where the HDB server SAR file are stored and extraction directories are created
sap_patching_hdb_server_base: /install/hanadb/server
# Directory where the SAR files are located (used during the prepare step)
sap_patching_hdb_server_source: "{{ sap_patching_hdb_server_base }}/source"

# Installation path of the HDB server (used to check the existing installation). Unless you have a weird non-standard installation, there is no need to set this variable.
sap_patching_hdb_server_install_path: "{{ '/usr/sap/' +  sap_patching_hdb_system_sid | upper  + '/SYS/exe/hdb' }}"

# If set the specified used will be used to perform the update. READ the documentation here: https://help.sap.com/docs/SAP_HANA_PLATFORM/2c1988d620e04368aa4103bf26f17727/df3de8c31cef45c0847d2804b97604ea.html
# to understand the implications of using this option (XSA update does not work with this option for example).
sap_patching_hdb_server_system_user:

# Password for the HANA user used to perform the update (this is the SYSTEM user unless defined otherwise in sap_patching_hdb_server_system_user)
sap_patching_hdb_server_system_user_password:

# If set to true, the system user (SYSTEM) will be activated prior to patching
# If set to false or not set, no action will be taken
sap_patching_hdb_server_activate_system_user: true
# HANA admin user store key (hdbuserstore) to use when activating the SYSTEM user
# If not set, sap_patching_hdb_server_activate_admin_user and sap_patching_hdb_server_activate_admin_password will be used instead
sap_patching_hdb_server_activate_admin_userstore_key:
# HANA admin user to use when activating the SYSTEM user
sap_patching_hdb_server_activate_admin_user:
# Password of the HANA admin user used when activating the SYSTEM user
sap_patching_hdb_server_activate_admin_password:

# If the database is clustered (currently only Redhat/Suse with Pacemaker are supported), set this to true. If SAP LinuxLab role `sap_ha_pacemaker_cluster` was used to setup the cluster, this doesn't need to be setup as the default value matches the naming convention used by the role.
sap_patching_hdb_server_is_clustered: false

# Name of the cluster resource for HDB server (used to relocate and put the resource in maintenance mode during patching). If SAP LinuxLab role `sap_ha_pacemaker_cluster` was used to setup the cluster AND HANA instance number is 00, this doesn't need to be setup as the default value matches the naming convention used by the role.
sap_patching_hdb_server_clu_hdb_resource_name: "cln_SAPHana_{{ sap_patching_hdb_system_sid | upper }}_HDB00"

# If true, the extracted HDB server source files are expected to be present on the local host (e.g. NFS share) following the execution of the prepare step.
# If false, the extracted HDB server source files will be copied from the Ansible controller to the target host
sap_patching_hdb_server_extracted_shared: true

# Where to store a local copy of extracted HDB server files as they must be present locally in order to run hdbinst
sap_patching_hdb_server_extracted_local_path: /install-local/hanadb/server


####################   Host agent patching settings   ####################
# See: https://help.sap.com/docs/host-agent/sap-host-agent-doc/sap-host-agent-upgrade?locale=en-US
# Base host agent directory where the host agent SAR file are stored and extraction directories are created
sap_patching_host_agent_base: /install/hostagents
# Directory where the SAR files are located (used during the prepare step)
sap_patching_host_agent_source: "{{ sap_patching_host_agent_base }}/source"

# If host agent autoupdate is configured (https://me.sap.com/notes/1473974) this is the path where it's looking for updates (parameter DIR_NEW in host_profile)
sap_patching_host_agent_autoupdate_path: /install/HostAgentUpdateDir

# If true, the extracted host agent files are expected to be present on the local host (e.g. NFS share) following the execution of the prepare step.
# If false, the extracted host agent files will be copied from the Ansible controller to the target host
sap_patching_host_agent_extracted_shared: true

# Where to store a local copy of extracted host agent files as they must be present locally in order to run saphostexec. This only applies to manual agent update.
sap_patching_host_agent_extracted_local_path: /install-local/hostagents


####################   Web disp patching settings   ####################
# Web disp SID
sap_patching_wdp_system_sid:

# Base web disp directory where the web disp SAR file are stored and extraction directories are created
sap_patching_webdisp_base: /install/webdisp
# Directory where the SAR files are located (used during the prepare step)
sap_patching_webdisp_source: "{{ sap_patching_webdisp_base }}/source"

# If true, the extracted web disp files are expected to be present on the local host (e.g. NFS share) following the execution of the prepare step.
# If false, the extracted web disp files will be copied from the Ansible controller to the target host
sap_patching_webdisp_extracted_shared: true


########################################################
# Generally no need to change anything below this line #
########################################################

# Global executable directory for the SAP kernel
# Generally no need to change this as it defaults to /usr/sap/<SID>/SYS/exe/run
sap_patching_kernel_global_exe:

# RKS wait timeout in seconds - must be more than rdisp/server_startup/max_time (default is 600 seconds)
sap_patching_rks_wait_timeout: 900

#########################################################
# Definitely no need to change anything below this line #
#########################################################

# Subfolders which stores the extracted files
sap_patching_kernel_extracted: extracted
sap_patching_hdb_client_extracted: extracted
sap_patching_hdb_server_extracted: extracted
sap_patching_host_agent_extracted: extracted
sap_patching_webdisp_extracted: extracted

# Name of symbolic link to point to the folder to be used by the patching process
sap_patching_kernel_to_apply_symlink: ansible_to_apply
sap_patching_hdb_client_to_apply_symlink: ansible_to_apply
sap_patching_hdb_server_to_apply_symlink: ansible_to_apply
sap_patching_host_agent_to_apply_symlink: ansible_to_apply
sap_patching_webdisp_to_apply_symlink: ansible_to_apply
