---
# Search for host agent SAR files and extract support package number
- name: Check if host agent source directory contains .sar files (case-insensitive)
  ansible.builtin.find:
    paths: "{{ sap_patching_host_agent_source }}"
    patterns: ['(?i)SAPHOSTAGENT.*\.SAR$']
    use_regex: true
    file_type: file
    recurse: false
  register: __sap_patching_register_host_agent_source_dir_content

# Only proceed if we've found some SAR files
- name: Prepare host agent files if SAR files are found
  when: __sap_patching_register_host_agent_source_dir_content.matched > 0
  block:
    # In case there are more than one SAR files, get the one with the highest version number
    - name: Get the highest version of host agent SAR file
      ansible.builtin.set_fact:
        __sap_patching_fact_host_agent_sar: >-
          {{
            __sap_patching_register_host_agent_source_dir_content.files
            | map(attribute='path')
            | map('basename')
            | sort
            | list
            | last
          }}

    - name: Check availability of SAPCAR - {{ sap_patching_sapcar_path + '/' + sap_patching_sapcar_file_name }}
      ansible.builtin.stat:
        path: "{{ sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}"
      register: __sap_patching_register_sapcar_file_name_stat
      failed_when: not __sap_patching_register_sapcar_file_name_stat.stat.exists

    - name: Extract the host agent version from SAR file
      ansible.builtin.set_fact:
        __sap_patching_fact_host_agent_version: "{{ __sap_patching_fact_host_agent_sar | regex_search('(?i)SAPHOSTAGENT([_\\d]+)-\\d+.SAR', '\\1') | list | last }}"

    - name: Set the target host agent directory variable
      ansible.builtin.set_fact:
        __sap_patching_fact_host_agent_extract_target: "{{ sap_patching_host_agent_base }}/{{ __sap_patching_host_agent_extracted }}_{{ __sap_patching_fact_host_agent_version }}"

    - name: Create target host agent directory
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_host_agent_extract_target }}"
        state: directory
        mode: '0755'
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      when:
        - __sap_patching_fact_host_agent_version != ''

    - name: Check target host agent directory
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_host_agent_extract_target }}"
      register: __sap_patching_register_host_agent_extract_target_stat

    - name: Assert that target host agent directory exists and is a directory
      ansible.builtin.assert:
        that:
          - __sap_patching_fact_host_agent_extract_target is defined
          - __sap_patching_register_host_agent_extract_target_stat.stat.exists
          - __sap_patching_register_host_agent_extract_target_stat.stat.isdir
        fail_msg: "Target host agent directory '{{ __sap_patching_fact_host_agent_extract_target }}' does not exist or is not a directory."
        success_msg: "Target host agent directory '{{ __sap_patching_fact_host_agent_extract_target }}' exists and is a directory."

    # Use shell globbing to move the files in case they are not in capitals as expected
    - name: Move all files from {{ sap_patching_host_agent_source }} to {{ sap_patching_host_agent_base }}
      changed_when: true
      ansible.builtin.shell: |
        mv '{{ sap_patching_host_agent_source }}'/[Ss][Aa][Pp][Hh][Oo][Ss][Tt][Aa][Gg][Ee][Nn][Tt]* '{{ sap_patching_host_agent_base }}'
      when:
        - sap_patching_host_agent_base is defined
        - sap_patching_host_agent_source is defined
        - sap_patching_host_agent_base != sap_patching_host_agent_source

    - name: Extract host agent SAR file to the target
      ansible.builtin.command: >-
        {{ sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}
        -xvf {{ sap_patching_host_agent_base }}/{{ __sap_patching_fact_host_agent_sar }}
        -R "{{ __sap_patching_fact_host_agent_extract_target }}"
        -manifest SIGNATURE.SMF
      register: __sap_patching_register_extract_result
      args:
        chdir: "{{ __sap_patching_fact_host_agent_extract_target }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"
      changed_when: "'SAPCAR: processing archive' in __sap_patching_register_extract_result.stdout"
      failed_when: __sap_patching_register_extract_result.rc != 0

    - name: Check that host agent extracted path exists
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_host_agent_extract_target }}/saphostexec"
      register: __sap_patching_register_host_agent_extracted_stat

    - name: Assert host agent extracted path exists
      ansible.builtin.assert:
        that:
          - __sap_patching_register_host_agent_extracted_stat.stat.exists
          - __sap_patching_register_host_agent_extracted_stat.stat.isreg
        fail_msg: "host agent directory '{{ __sap_patching_fact_host_agent_extract_target }}/saphostexec' does not exist."
        success_msg: "host agent directory '{{ __sap_patching_fact_host_agent_extract_target }}/saphostexec' exists"

    - name: Ensure symbolic link for host agent directory is correct
      ansible.builtin.file:
        src: "{{ __sap_patching_fact_host_agent_extract_target }}"
        dest: "{{ sap_patching_host_agent_base }}/{{ sap_patching_host_agent_to_apply_symlink }}"
        state: link
        force: true
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"

    - name: Set sap_patching_host_agent_to_apply variable for use in later tasks
      ansible.builtin.set_fact:
        sap_patching_host_agent_to_apply: "{{ __sap_patching_fact_host_agent_extract_target }}"
