
- name: Setting correct variables for restart task
  set_fact:
    _sap_patching_sap_system_sid: "{{ sap_patching_sap_system_sid }}"
    _sap_patching_kernel_restart_strategy: "{{ sap_patching_kernel_restart_strategy }}"
    _sap_patching_kernel_or_webdisp: "abap_kernel"

- name: Execute kernel restart function to restart the system
  ansible.builtin.include_tasks:
    file: xnw_kernel_restart.yml
