# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Patching - Kernel - Prepare - Stat availability of the kernel base directory with user {{ sap_patching_file_owner }}
  ansible.builtin.stat:
    path: "{{ __sap_patching_kernel_base }}"
  register: __sap_patching_register_kernel_base_stat
  # Stat with correct user to check permissions.
  become: true
  become_user: "{{ sap_patching_file_owner }}"

- name: SAP Patching - Kernel - Prepare - Fail if user cannot write to kernel base directory
  ansible.builtin.fail:
    msg: |
      FAIL: User '{{ sap_patching_file_owner }}' does not have write permissions
      to the directory '{{ sap_patching_kernel_base }}'
      defined in the variable 'sap_patching_kernel_base'.

      Ansible cannot create the symlink '{{ sap_patching_kernel_to_apply_symlink }}'
      without write access to this path.
      Please check the directory permissions (chmod/chown).
  when: not __sap_patching_register_kernel_base_stat.stat.writeable

# Search for kernel SAR files and extract support package number
- name: SAP Patching - Kernel - Prepare - Find .sar files in the kernel source directory (case-insensitive)
  ansible.builtin.find:
    paths: "{{ __sap_patching_kernel_source }}"
    patterns: ['(?i).*\.sar$']
    use_regex: true
    file_type: file
    recurse: false
  register: __sap_patching_register_kernel_source_dir_content


- name: Block to execute only if SAR files were found
  when: __sap_patching_register_kernel_source_dir_content.matched | d(0) > 0
  block:

    # Fail first if duplicate SAR files are found.
    - name: SAP Patching - Kernel - Prepare - Fail if duplicate SAR files are found in source directory
      ansible.builtin.fail:
        msg: |
          FAIL: Duplicates SAR file prefixes were detected!
          File prefixes ({{ __all_files | length }}): {{ __all_files | join(', ') }}
          Unique prefixes ({{ __all_files | unique | length }}): {{ __all_files | unique | join(', ') }}
      vars:
        __all_files: >-
          {{ __sap_patching_register_kernel_source_dir_content.files
            | map(attribute='path')
            | map('basename')
            | map('regex_replace', '^(.+?)_.*$', '\1')
            | list }}
      when: __all_files | length != __all_files | unique | length

    - name: SAP Patching - Kernel - Prepare - Find SAPEXE* or dw* SAR files
      ansible.builtin.find:
        paths: "{{ __sap_patching_kernel_source }}"
        patterns:
          - '(?i)SAPEXE_\d+-.*\.SAR'
          - '(?i)SAPEXEDB_\d+-.*\.SAR'
          - '(?i)dw_\d+-.*\.SAR'
        use_regex: true
        file_type: file
      register: __sap_patching_register_kernel_exedw_files


    - name: SAP Patching - Kernel - Prepare - Set facts to enable append mode if no SAPEXE/dw SAR files are found
      ansible.builtin.set_fact:
        __sap_patching_kernel_normal_mode: false
        __sap_patching_kernel_append_mode: true
      when:
        - __sap_patching_register_kernel_exedw_files.matched | int == 0
        - sap_patching_kernel_prepare_append_to_version | d('', true) | length > 0
        - sap_patching_kernel_prepare_append_to_version is match("\\d+p\\d+")

    - name: SAP Patching - Kernel - Prepare - Set facts to enable delta mode if no SAPEXE SAR files are found but dw SAR files exist
      ansible.builtin.set_fact:
        __sap_patching_kernel_normal_mode: false
        __sap_patching_kernel_delta_mode: true
      when:
        - __sap_patching_register_kernel_exedw_files.matched | int > 0
        - __sap_patching_register_kernel_exedw_files.files | selectattr('path', 'search', '(?i)SAPEXE_.*\.SAR') | list | length == 0
        - __sap_patching_register_kernel_exedw_files.files | selectattr('path', 'search', '(?i)SAPEXEDB_.*\.SAR') | list | length == 0


    - name: SAP Patching - Kernel - Prepare - Fail if append mode is not enabled and no SAPEXE/dw SAR files are found
      ansible.builtin.fail:
        msg: |
          FAIL: Core Kernel SAR files (SAPEXE/SAPEXEDB/dw) are missing and Append Mode is not correctly configured.
          No files matching the expected patterns were found in '{{ __sap_patching_kernel_source }}'.
          Expected file name patterns include:
          - 'SAPEXE_<patch>*.SAR'
          - 'SAPEXEDB_<patch>*.SAR'
          - 'dw_<patch>*.SAR'

          How to resolve this issue:
          1. Provide Core SAR files: Ensure files are present and follow the naming convention described above.
          2. Enable Append Mode: Set the variable 'sap_patching_kernel_prepare_append_to_version' to the target version (Example: '753p100').
             Current variable value: '{{ sap_patching_kernel_prepare_append_to_version | default("NOT SET") }}'
      when:
        - __sap_patching_register_kernel_exedw_files.matched | int == 0
        - not __sap_patching_kernel_append_mode

    - name: SAP Patching - Kernel - Prepare - Fail if append mode is enabled and SAPEXE/dw SAR files are found
      ansible.builtin.fail:
        msg: |
          FAIL: Conflict detected between Core SAR files and Append Mode configuration.
          Core Kernel SAR files (SAPEXE/SAPEXEDB/dw) were found in '{{ __sap_patching_kernel_source }}',
          but 'sap_patching_kernel_prepare_append_to_version' is also set.

          How to resolve this issue:
          1. Use Normal Patching Mode: Unset or clear the variable 'sap_patching_kernel_prepare_append_to_version'.
             Current variable value: '{{ sap_patching_kernel_prepare_append_to_version | default("NOT SET") }}'
          2. Use Append Mode: Remove the Core SAR files from the source directory if you only intended
             to append delta patches (like IGS or Libs) to an existing kernel.
      when:
        - __sap_patching_register_kernel_exedw_files.matched | int > 0
        - __sap_patching_kernel_append_mode


    - name: Block for normal and delta modes
      when: not __sap_patching_kernel_append_mode
      block:

        # Default 'TMP' is used only for folder creation in normal and delta modes.
        - name: SAP Patching - Kernel - Prepare - Set fact with extracted highest patch number from file names
          ansible.builtin.set_fact:
            __sap_patching_fact_kernel_pn:
              "{{ (__sap_patching_register_kernel_exedw_files.files
                | map(attribute='path')
                | map('basename')
                | map('regex_search', '_(\\d+)-', '\\1')
                | map('first')
                | map('int')
                | sort
                | last) | d('TMP') }}"

        - name: SAP Patching - Kernel - Prepare - Set fact with extracted kernel directory
          ansible.builtin.set_fact:
            __sap_patching_fact_kernel_extract_target:
              "{{ __sap_patching_kernel_base }}/k{{ __kernel_release }}p{{ __sap_patching_fact_kernel_pn }}"
          vars:
            __kernel_release:
              "{{ sap_patching_kernel_prepare_version if sap_patching_kernel_prepare_version | lower != 'autodetect' else 'TMP' }}"

        # Directory is created only in normal and delta modes.
        - name: SAP Patching - Kernel - Prepare - Create a target kernel directory
          ansible.builtin.file:
            path: "{{ __sap_patching_fact_kernel_extract_target }}"
            state: directory
            mode: '0755'
            owner: "{{ sap_patching_file_owner }}"
            group: "{{ sap_patching_file_group }}"


    - name: Block for append mode
      when: __sap_patching_kernel_append_mode
      block:

        - name: SAP Patching - Kernel - Prepare - Set fact with extracted patch number from the variable in append mode
          ansible.builtin.set_fact:
            __sap_patching_fact_kernel_pn:
              "{{ sap_patching_kernel_prepare_append_to_version | regex_search('^\\d+p(\\d+)$', '\\1') | first | int }}"

        - name: SAP Patching - Kernel - Prepare - Set fact with extracted kernel directory
          ansible.builtin.set_fact:
            __sap_patching_fact_kernel_extract_target:
              "{{ __sap_patching_kernel_base }}/k{{ sap_patching_kernel_prepare_append_to_version }}"

        # We check if kernel directory exists only in append mode, because in non-append mode we will create the directory.
        - name: SAP Patching - Kernel - Prepare - Stat availability of target kernel directory
          ansible.builtin.stat:
            path: "{{ __sap_patching_fact_kernel_extract_target }}"
          register: __sap_patching_register_kernel_extract_target_stat

        - name: SAP Patching - Kernel - Prepare - Fail if target kernel directory does not exist or is not a directory
          ansible.builtin.fail:
            msg: |
              FAIL: Target kernel directory '{{ __sap_patching_fact_kernel_extract_target }}' does not exist or is not a directory.
          when: not (__sap_patching_register_kernel_extract_target_stat.stat.exists
                  and __sap_patching_register_kernel_extract_target_stat.stat.isdir)


    - name: SAP Patching - Kernel - Prepare - Copy kernel files to target directory
      ansible.builtin.copy:
        src: "{{ __sap_patching_kernel_source }}/"  # Trailing slash is required.
        dest: "{{ __sap_patching_fact_kernel_extract_target }}/"
        remote_src: true
        mode: 'preserve'
      when: __sap_patching_fact_kernel_extract_target != __sap_patching_kernel_source

    - name: SAP Patching - Kernel - Prepare - Prepare directory for kernel extraction
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_kernel_extract_target }}/{{ __sap_patching_kernel_extracted }}"
        state: directory
        mode: '0755'
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      when: not __sap_patching_kernel_append_mode


    - name: SAP Patching - Kernel - Prepare - Set fact with prepared ordered list of kernel SAR files (SAPEXE*, SAPEXEDB* first)
      ansible.builtin.set_fact:
        __sap_patching_ordered_kernel_sar_files: >-
          {{
            (
              __sap_patching_register_kernel_source_dir_content.files
              | selectattr('path', 'search', '(?i)SAPEXE_.*\.SAR')
              | list
              +
              __sap_patching_register_kernel_source_dir_content.files
              | selectattr('path', 'search', '(?i)SAPEXEDB_.*\.SAR')
              | list
              +
              __sap_patching_register_kernel_source_dir_content.files
              | rejectattr('path', 'search', '(?i)SAPEXE_.*\.SAR')
              | rejectattr('path', 'search', '(?i)SAPEXEDB_.*\.SAR')
              | list
            )
          }}

    - name: SAP Patching - Kernel - Prepare - Extract kernel SAR files in the correct order
      ansible.builtin.command:
        cmd: >-
          {{ __sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}
          -xvf {{ file_item.path | basename }}
          -R "{{ __sap_patching_fact_kernel_extract_target }}/{{ __sap_patching_kernel_extracted }}"
          -manifest SIGNATURE.SMF
      args:
        chdir: "{{ __sap_patching_fact_kernel_extract_target }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"
      loop: "{{ __sap_patching_ordered_kernel_sar_files }}"
      loop_control:
        label: "{{ file_item.path | basename }}"
        loop_var: file_item
      register: __sap_patching_register_extract_result
      changed_when: "'SAPCAR: processing archive' in __sap_patching_register_extract_result.stdout"


    - name: SAP Patching - Kernel - Prepare - Set fact with LD_LIBRARY_PATH for kernel extraction
      ansible.builtin.set_fact:
        __sap_patching_fact_ld_library_path:
          "{{ __sap_patching_fact_kernel_extract_target }}/{{ __sap_patching_kernel_extracted }}"

    # NOTE: dw_ file does not contain all necessary libraries for disp+work.
    # We have to combine the extracted kernel path with the original LD_LIBRARY_PATH to ensure all necessary libraries are available for disp+work.
    - name: SAP Patching - Kernel - Prepare - Set fact with updated LD_LIBRARY_PATH for kernel extraction in delta mode
      ansible.builtin.set_fact:
        __sap_patching_kernel_fact_delta_suffix: "-delta"
        __sap_patching_fact_ld_library_path:
          "{{ __sap_patching_fact_ld_library_path }}:/usr/sap/{{ sap_patching_sap_system_sid | upper }}/SYS/exe/run/"
      when:
        - sap_patching_kernel_prepare_version | lower == 'autodetect'
        - __sap_patching_kernel_delta_mode


    # Not going to use sapcontrol -nr 00 -function GetVersionInfo
    - name: SAP Patching - Kernel - Prepare - Check kernel release and patch number using disp+work in extracted kernel directory
      ansible.builtin.shell:
        cmd: >
          set -o pipefail &&
          {{ __sap_patching_fact_kernel_extract_target }}/{{ __sap_patching_kernel_extracted }}/disp+work
      environment:
        LD_LIBRARY_PATH: "{{ __sap_patching_fact_ld_library_path }}"
      register: __sap_patching_register_disp_work_output
      changed_when: false

    - name: SAP Patching - Kernel - Prepare - Fail if 'disp+work' command failed in the extracted kernel directory
      ansible.builtin.fail:
        msg: |
          FAIL: The command 'disp+work' has failed in the extracted kernel directory.
          Output: {{ __sap_patching_register_disp_work_output.stdout | d('') }}
          Error: {{ __sap_patching_register_disp_work_output.stderr | d('') }}
      when: __sap_patching_register_disp_work_output.rc != 0


    - name: SAP Patching - Kernel - Prepare - Set facts with extracted kernel release and patch number from disp+work output
      ansible.builtin.set_fact:
        __sap_patching_fact_kernel_release_dw:
          "{{ __sap_patching_register_disp_work_output.stdout | regex_search('kernel release\\s+(\\d+)', '\\1') | first | d('0') }}"
          # "{{ __sap_patching_register_disp_work_output.stdout_lines | select('search', '^kernel release')
          #   | list | first | regex_search('kernel release\\s+(\\d+)', '\\1') | first }}"
        __sap_patching_fact_kernel_patch_dw:
          "{{ __sap_patching_register_disp_work_output.stdout | regex_search('patch number\\s+(\\d+)', '\\1') | first | d('0') }}"
          # "{{ __sap_patching_register_disp_work_output.stdout_lines | select('search', '^patch number')
          #   | list | first | regex_search('patch number\\s+(\\d+)', '\\1') | first }}"

    - name: SAP Patching - Kernel - Prepare - Fail if expected kernel patch number does not match extracted SAR patch number
      ansible.builtin.fail:
        msg: |
          FAIL: Mismatch between kernel patch number extracted from disp+work and expected patch number from SAR file names.
          File name patch number: {{ __sap_patching_fact_kernel_pn }}
          Disp+work patch number: {{ __sap_patching_fact_kernel_patch_dw }}
        when: not ((__sap_patching_fact_kernel_patch_dw | int) == (__sap_patching_fact_kernel_pn | int))


    # We copy first, then remove, because Ansible does not have builtin move module.
    - name: Block to move temporary kernel directory
      when:
        - sap_patching_kernel_prepare_version | lower == 'autodetect'
        - not __sap_patching_kernel_append_mode
      block:
        - name: SAP Patching - Kernel - Prepare - Copy temporary kernel directory contents to final destination
          ansible.builtin.copy:
            src: "{{ __sap_patching_kernel_base }}/kTMPp{{ __sap_patching_fact_kernel_pn }}/"
            dest: "{{ __sap_patching_kernel_base }}/k{{ __sap_patching_fact_kernel_release_dw }}p{{
              __sap_patching_fact_kernel_pn }}{{ __sap_patching_kernel_fact_delta_suffix | d('') }}/"
            remote_src: true
            mode: '0755'
            owner: "{{ sap_patching_file_owner }}"
            group: "{{ sap_patching_file_group }}"

        - name: SAP Patching - Kernel - Prepare - Remove the temporary kernel directory
          ansible.builtin.file:
            path: "{{ __sap_patching_kernel_base }}/kTMPp{{ __sap_patching_fact_kernel_pn }}"
            state: absent

        - name: SAP Patching - Kernel - Prepare - Set fact with updated target kernel SP directory variable
          ansible.builtin.set_fact:
            __sap_patching_fact_kernel_extract_target:
              "{{ __sap_patching_kernel_base }}/k{{ __sap_patching_fact_kernel_release_dw }}p{{
                __sap_patching_fact_kernel_pn }}{{ __sap_patching_kernel_fact_delta_suffix | d('') }}"


    - name: SAP Patching - Kernel - Prepare - Fail if kernel release does not match user defined version in 'sap_patching_kernel_prepare_version'
      ansible.builtin.fail:
        msg: |
          FAIL: Mismatch between kernel release extracted from disp+work and the variable 'sap_patching_kernel_prepare_version'.
          User defined release: {{ sap_patching_kernel_prepare_version }}
          Disp+work kernel release: {{ __sap_patching_fact_kernel_release_dw }}
      when:
        - sap_patching_kernel_prepare_version | lower != 'autodetect'
        - not __sap_patching_kernel_append_mode
        - __sap_patching_fact_kernel_release_dw | int != sap_patching_kernel_prepare_version | int


    - name: SAP Patching - Kernel - Prepare - Create symbolic link for further execution tasks
      ansible.builtin.file:
        src: "{{ __sap_patching_fact_kernel_extract_target }}/{{ __sap_patching_kernel_extracted }}"
        dest: "{{ __sap_patching_kernel_base }}/{{ sap_patching_kernel_to_apply_symlink }}"
        state: link
        force: true
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"
      when: not __sap_patching_kernel_append_mode


    # This needs to be last so that sap_patching_kernel_to_apply is set correctly
    # as the symlink step above needs the default value
    # NOTE: This will not override user defined variable due to variable precedence!
    - name: SAP Patching - Kernel - Prepare - Set fact with prepared path for further execution tasks
      ansible.builtin.set_fact:
        sap_patching_kernel_to_apply:
          "{{ __sap_patching_fact_kernel_extract_target }}/{{ __sap_patching_kernel_extracted }}"


  # Cleanup all folders created during kernel preparation in case of failure to avoid leaving the system in an inconsistent state.
  rescue:
    - name: SAP Patching - Kernel - Prepare - Cleanup - Remove target kernel directory in case of failure
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_kernel_extract_target }}"
        state: absent
      when: __sap_patching_fact_kernel_extract_target is defined

    - name: SAP Patching - Kernel - Prepare - Fail if preparation tasks have failed
      ansible.builtin.fail:
        msg: |
          FAIL: Kernel preparation tasks have failed.
          All created folders during kernel preparation have been removed.
          Please review the error messages above to identify the root cause of the failure
          and re-run the playbook after resolving the issue.


- name: SAP Patching - Kernel - Prepare - Inform that SAR files were not found
  ansible.builtin.debug:
    msg: |
      No kernel SAR files found in source directory {{ __sap_patching_kernel_source }}.
      Skipping kernel preparation.
  when: __sap_patching_register_kernel_source_dir_content.matched == 0
