# SPDX-License-Identifier: Apache-2.0
---

# Shared task file for both ABAP Kernel and Web Dispatcher Kernel patching.

# Explanation for validation handling in apply tasks:
# 1. Patching file validations must be executed and fail if not valid.
# 2. Apply tasks can be skipped if target host is missing the target directory.
# This ensures that all hosts in play are ready for patching, but only valid hosts will be patched.
# Example for distributed HA system: Kernel patched only on Application servers, while HDB server patched only on Database servers.

# Prepare tasks are doing validation already, but apply can be executed without prepare, so validation must happen again.
- name: SAP Patching - Kernel - Apply - Stat availability of the base directory
  ansible.builtin.stat:
    path: "{{ __sap_patching_fact_kernel_base }}"
  register: __sap_patching_register_kernel_apply_base_stat

- name: SAP Patching - Kernel - Apply - Fail if user cannot write to base directory
  ansible.builtin.fail:
    msg: |
      FAIL: The path "{{ __sap_patching_fact_kernel_base }}" does not exist or is not a directory.
      {% if __sap_patching_fact_kernel_type == 'abap_kernel' %}
      Please ensure that the path defined in the variable 'sap_patching_kernel_base' is a directory.
      {% else %}
      Please ensure that the path defined in the variable 'sap_patching_webdisp_base' is a directory.
      {% endif %}
  when: not (__sap_patching_register_kernel_apply_base_stat.stat.exists
          and __sap_patching_register_kernel_apply_base_stat.stat.isdir)


# Load version to apply in this order:
# 1. If '__sap_patching_fact_kernel_to_apply_user' is not empty.
# 2. If '__sap_patching_fact_kernel_to_apply' is not defined. We assume prepare was executed.
# 3. Default symlink '__sap_patching_fact_kernel_to_apply_symlink_user'.
- name: SAP Patching - Kernel - Apply - Set fact with kernel symlink if kernel is not specified
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_to_apply: >-
      {{ __sap_patching_fact_kernel_to_apply_user | regex_replace('\\/$', '')
        if __sap_patching_fact_kernel_to_apply_user | string | trim | length > 0
        else (__sap_patching_fact_kernel_to_apply
          if __sap_patching_fact_kernel_to_apply | string | trim | length > 0
          else __sap_patching_fact_kernel_to_apply_symlink_user) }}

- name: SAP Patching - Kernel - Apply - Set fact with updated kernel path if it is not an absolute path
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_to_apply:
      "{{ __sap_patching_fact_kernel_base }}/{{ __sap_patching_fact_kernel_to_apply }}"
  when: not __sap_patching_fact_kernel_to_apply.startswith('/')

# - name: Append __sap_patching_kernel_extracted to sap_patching_kernel_to_apply if not present
#   ansible.builtin.set_fact:
#     __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_to_apply }}/{{ __sap_patching_kernel_extracted }}"
#   when:
#     - __sap_patching_fact_kernel_to_apply is defined
#     - __sap_patching_fact_kernel_type == "abap_kernel"
#     - not __sap_patching_fact_kernel_to_apply | regex_search('(^|/)' ~ __sap_patching_kernel_extracted ~ '(/|$)')


# Prepare tasks prepared all files on all managed nodes, or on first one with shared filesystem.
- name: SAP Patching - Kernel - Apply - Stat availability of extracted kernel directory
  ansible.builtin.stat:
    path: "{{ __sap_patching_fact_kernel_to_apply }}"
  register: __sap_patching_register_kernel_to_apply_stat

- name: SAP Patching - Kernel - Apply - Fail if kernel path does not exist and is not a directory or symlink
  ansible.builtin.fail:
    msg: |
      FAIL: The specified kernel path "{{ __sap_patching_fact_kernel_to_apply }}" is not a directory or symlink.
      Please ensure that the kernel files have been extracted to the shared folder
      and the variable 'sap_patching_kernel_to_apply' is set correctly.
  when: not __sap_patching_register_kernel_to_apply_stat.stat.exists
          or not (__sap_patching_register_kernel_to_apply_stat.stat.isdir
            or __sap_patching_register_kernel_to_apply_stat.stat.islnk)

- name: SAP Patching - Kernel - Apply - Check the content of '{{ __sap_patching_fact_kernel_to_apply }}'
  ansible.builtin.find:
    paths: "{{ __sap_patching_fact_kernel_to_apply }}"
    file_type: file
  register: __sap_patching_register_kernel_to_apply_files

- name: SAP Patching - Kernel - Apply - Fail if the kernel directory is empty
  ansible.builtin.fail:
    msg: |
      FAIL: The directory "{{ __sap_patching_fact_kernel_to_apply }}" is empty and patching cannot proceed!
      Ensure that the kernel SAR files have been extracted to the shared folder and re-run the playbook.
  when: __sap_patching_register_kernel_to_apply_files.matched | int == 0


- name: SAP Patching - Kernel - Apply - Set fact with global exe directory
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_global_exe:
      "/usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/SYS/exe/run"

- name: SAP Patching - Kernel - Apply - Stat availability of the global exe directory {{ __sap_patching_fact_kernel_global_exe }}
  ansible.builtin.stat:
    path: "{{ __sap_patching_fact_kernel_global_exe }}"
  register: __sap_patching_register_sapmnt_exe_stat

# Validate presence of the global exe directory and its content to determine if patching can proceed.
- name: Block to identify if patching can proceed
  when:
    - __sap_patching_register_sapmnt_exe_stat.stat.exists
    - __sap_patching_register_sapmnt_exe_stat.stat.islnk
      or __sap_patching_register_sapmnt_exe_stat.stat.isdir
  block:
    - name: SAP Patching - Kernel - Apply - Find files in the global exe directory {{ __sap_patching_fact_kernel_global_exe }}
      ansible.builtin.find:
        paths: "{{ __sap_patching_fact_kernel_global_exe }}"
        file_type: file
      register: __sap_patching_register_sapmnt_exe_files

    - name: SAP Patching - Kernel - Apply - Fail if global exe directory is empty
      ansible.builtin.fail:
        msg: |
          FAIL: The global exe directory "{{ __sap_patching_fact_kernel_global_exe }}" was found, but it is empty!
          This indicates that the targeted SAP system is not correctly installed and patching cannot proceed!
          Ensure that targeted SAP system is correctly installed.
      when: __sap_patching_register_sapmnt_exe_files.matched | int == 0

    - name: SAP Patching - Kernel - Apply - Set fact if patching can proceed
      ansible.builtin.set_fact:
        __sap_patching_fact_kernel_is_ready: true
      when: __sap_patching_register_sapmnt_exe_files.matched | int > 0


# Use previous validation to silently skip hosts without kernel/webdisp present)
- name: Block for kernel apply execution when global exe directory is present
  when: __sap_patching_fact_kernel_is_ready | d(false)
  block:
    - name: SAP Patching - Kernel - Apply - Copy kernel files to global exe directory
      ansible.builtin.copy:
        src: "{{ __sap_patching_fact_kernel_to_apply }}/"
        dest: "{{ __sap_patching_fact_kernel_global_exe }}"
        remote_src: true  # Files are already on the managed node, just move them with correct permissions.
        owner: "{{ __sap_patching_fact_sidadm_user }}"
        group: sapsys
        mode: '0755'
        directory_mode: '0755'
      changed_when: true

  # This rescue block cannot remove any files in current form, because backup is not implemented.
  # TODO: Add global exe backup tasks that can be used in rescue block to restore original state.
  rescue:
    - name: SAP Patching - Kernel - Apply - Fail if kernel patching tasks have failed
      ansible.builtin.fail:
        msg: |
          FAIL: Kernel patching tasks have failed.
          Please review the error messages above to identify the root cause of the failure
          and re-run the playbook after resolving the issue.


- name: SAP Patching - Kernel - Apply - Warning about skipped patching
  ansible.builtin.debug:
    msg: |
      WARN: Kernel patching tasks have been skipped because:
      - The global exe directory "{{ __sap_patching_fact_kernel_global_exe }}" does not exist as a directory or symlink.
      This is expected behavior on hosts where the kernel is not installed (e.g. database servers).
  when: not __sap_patching_fact_kernel_is_ready | d(false)
