# SPDX-License-Identifier: Apache-2.0
---

# Shared task file for both ABAP Kernel and Web Dispatcher Kernel patching.

- name: SAP Patching - Kernel - Saproot - Stat availability of saproot.sh file
  ansible.builtin.stat:
    path: /usr/sap/{{ __sap_patching_fact_sap_system_sid }}/SYS/exe/run/saproot.sh
  register: __sap_patching_register_kernel_saproot_sh_stat

# Reason for noqa: Shell retains the environment variables.
- name: SAP Patching - Kernel - Saproot - Execute saproot.sh to adjust permissions after patching if available  # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: >-
      /usr/sap/{{ __sap_patching_fact_sap_system_sid }}/SYS/exe/run/saproot.sh
      {{ __sap_patching_fact_sap_system_sid }}
  become: true  # Saproot is executed as root user
  register: __sap_patching_register_kernel_saproot
  changed_when: __sap_patching_register_kernel_saproot.rc == 0
  when:
    - __sap_patching_register_kernel_saproot_sh_stat.stat.exists
    - __sap_patching_register_kernel_saproot_sh_stat.stat.mode is search('..7$|..5$|..1$')
  failed_when: false  # Fail is handled in the next task using '.rc' instead of '.failed'.

- name: SAP Patching - Kernel - Saproot - Fail if 'saproot' command has failed
  ansible.builtin.fail:
    msg: |
      FAIL: The command 'saproot' has failed for current kernel.
      Command: {{ __sap_patching_register_kernel_saproot.cmd | d('') }}
      Output: {{ __sap_patching_register_kernel_saproot.stdout | d('') }}
      Error: {{ __sap_patching_register_kernel_saproot.stderr | d('') }}
  when:
    - __sap_patching_register_kernel_saproot.rc is defined
    - __sap_patching_register_kernel_saproot.rc != 0
