---
# Search for webdisp SAR files and extract support package number
- name: Check if webdisp source directory contains .sar files (case-insensitive)
  ansible.builtin.find:
    paths: "{{ sap_patching_webdisp_source }}"
    patterns: ['(?i)sapwebdisp_.*\.sar$']
    use_regex: true
    file_type: file
    recurse: false
  register: __sap_patching_register_webdisp_source_dir_content

# Only proceed if we've found some SAR files
- name: Proceed with web dispatcher preparation if SAR files are found
  when: __sap_patching_register_webdisp_source_dir_content.matched > 0
  block:
    # In case there are more than one SAR files, get the one with the highest version number
    - name: Get the highest version of web dispatcher SAR file
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_sar: >-
          {{
            __sap_patching_register_webdisp_source_dir_content.files
            | map(attribute='path')
            | map('basename')
            | sort
            | list
            | last
          }}

    - name: Check availability of SAPCAR - {{ sap_patching_sapcar_path + '/' + sap_patching_sapcar_file_name }}
      ansible.builtin.stat:
        path: "{{ sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}"
      register: __sap_patching_register_sapcar_file_name_stat
      failed_when: not __sap_patching_register_sapcar_file_name_stat.stat.exists

    - name: Extract the web dispatcher version from SAR file
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_pn: "{{ __sap_patching_fact_webdisp_sar | regex_search('(?i)SAPWEBDISP_SP_(\\d+)-\\d+.SAR', '\\1') | list | last }}"

    - name: Set the target web dispatcher directory variable
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_extract_target: "{{ sap_patching_webdisp_base }}/{{ __sap_patching_webdisp_extracted }}_{{ __sap_patching_fact_webdisp_pn }}"

    - name: Create target web dispatcher directory
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}"
        state: directory
        mode: '0755'
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      when:
        - __sap_patching_fact_webdisp_pn != ''

    - name: Check target web dispatcher directory
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}"
      register: __sap_patching_register_webdisp_extract_target_stat

    - name: Assert that target web dispatcher directory exists and is a directory
      ansible.builtin.assert:
        that:
          - __sap_patching_register_webdisp_extract_target is defined
          - __sap_patching_register_webdisp_extract_target_stat.stat.exists
          - __sap_patching_register_webdisp_extract_target_stat.stat.isdir
        fail_msg: "Target web dispatcher directory '{{ __sap_patching_fact_webdisp_extract_target }}' does not exist or is not a directory."
        success_msg: "Target web dispatcher directory '{{ __sap_patching_fact_webdisp_extract_target }}' exists and is a directory."

    # Use shell globbing to move the files in case they are not in capitals as expected
    - name: Move all files from {{ sap_patching_webdisp_source }} to {{ sap_patching_webdisp_base }}
      ansible.builtin.shell: |
        mv '{{ sap_patching_webdisp_source }}'/[Ss][Aa][Pp][Ww][Ee][Bb][Dd][Ii][Ss][Pp]* '{{ sap_patching_webdisp_base }}'
      when:
        - sap_patching_webdisp_base is defined
        - sap_patching_webdisp_source is defined
        - sap_patching_webdisp_base != sap_patching_webdisp_source
      changed_when: true

    - name: Extract web dispatcher SAR file to the target
      ansible.builtin.command: >-
        {{ sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}
        -xvf {{ sap_patching_webdisp_base }}/{{ __sap_patching_fact_webdisp_sar }}
        -R "{{ __sap_patching_fact_webdisp_extract_target }}"
        -manifest SIGNATURE.SMF
      register: __sap_patching_register_extract_result
      args:
        chdir: "{{ __sap_patching_fact_webdisp_extract_target }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"
      changed_when: "'SAPCAR: processing archive' in __sap_patching_register_extract_result.stdout"
      failed_when: __sap_patching_register_extract_result.rc != 0

    - name: Check that web dispatcher extracted path exists
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp"
      register: __sap_patching_register_webdisp_extracted_stat

    - name: Assert web dispatcher extracted path exists
      ansible.builtin.assert:
        that:
          - __sap_patching_register_webdisp_extracted_stat.stat.exists
          - __sap_patching_register_webdisp_extracted_stat.stat.isreg
        fail_msg: "web dispatcher directory '{{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp' does not exist."
        success_msg: "web dispatcher directory '{{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp' exists"

    - name: Check webdisp release and patch number
      ansible.builtin.shell: >
        set -o pipefail && {{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp -v | grep 'kernel release\|patch number'
      environment:
        LD_LIBRARY_PATH: "{{ __sap_patching_fact_webdisp_extract_target }}"
      register: __sap_patching_register_webdisp_release_patch_output
      changed_when: false
      failed_when: __sap_patching_register_webdisp_release_patch_output.rc != 0

    # webdisp is using = between release/patch and the number unlike disp+work which is using just spaces
    - name: Extract webdisp release and patch number from sapwebdisp output
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_release_wd: "{{ __sap_patching_register_webdisp_release_patch_output.stdout_lines | select('search', '^kernel release') | list | first | regex_search('kernel release\\s+=+\\s+(\\d+)', '\\1') | first }}"
        __sap_patching_fact_webdisp_patch_wd: "{{ __sap_patching_register_webdisp_release_patch_output.stdout_lines | select('search', '^patch number') | list | first | regex_search('patch number\\s+=+\\s+(\\d+)', '\\1') | first }}"

    - name: Assert expected webdisp patch number matches extracted SAR patch number
      ansible.builtin.assert:
        that:
          - (__sap_patching_fact_webdisp_patch_wd | int) == (__sap_patching_fact_webdisp_pn | int)
        fail_msg: "Web disp patch number ({{ __sap_patching_fact_webdisp_patch_wd }}) does not match expected SAR patch number ({{ __sap_patching_fact_webdisp_pn }})."

    - name: Rename webdisp directory
      ansible.builtin.command: >
        mv "{{ __sap_patching_fact_webdisp_extract_target }}"
           "{{ sap_patching_webdisp_base }}/{{ __sap_patching_webdisp_extracted }}_{{ __sap_patching_fact_webdisp_release_wd }}p{{ __sap_patching_fact_webdisp_pn }}"
      changed_when: true

    - name: Update target webdisp SP directory variable after rename - autodetect mode
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_extract_target: "{{ sap_patching_webdisp_base }}/{{ __sap_patching_webdisp_extracted }}_{{ __sap_patching_fact_webdisp_release_wd }}p{{ __sap_patching_fact_webdisp_pn }}"

    - name: Ensure symbolic link for web dispatcher directory is correct
      ansible.builtin.file:
        src: "{{ __sap_patching_fact_webdisp_extract_target }}"
        dest: "{{ sap_patching_webdisp_base }}/{{ sap_patching_webdisp_to_apply_symlink }}"
        state: link
        force: true
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"

    - name: Set sap_patching_webdisp_to_apply variable for use in later tasks
      ansible.builtin.set_fact:
        sap_patching_webdisp_to_apply: "{{ __sap_patching_fact_webdisp_extract_target }}"
