---
- name: Setting correct variables for saproot task
  ansible.bultin.set_fact:
    _sap_patching_sap_system_sid: "{{ sap_patching_wdp_system_sid }}"

- name: Execute saproot function to set correct permissions
  ansible.builtin.include_tasks:
    file: xnw_kernel_saproot.yml
