# SPDX-License-Identifier: Apache-2.0
---

# Search for webdisp SAR files and extract support package number
- name: SAP Patching - Web Dispatcher - Prepare - Check if webdisp source directory contains .sar files (case-insensitive)
  ansible.builtin.find:
    paths: "{{ sap_patching_webdisp_source }}"
    patterns: ['(?i)sapwebdisp_.*\.sar$']
    use_regex: true
    file_type: file
    recurse: false
  register: __sap_patching_register_webdisp_source_dir_content


- name: Block if sar files were found
  when: __sap_patching_register_webdisp_source_dir_content.matched > 0
  block:

    # In case there are more than one SAR files, get the one with the highest version number
    # NOTE: This differs to kernel prepare steps as multiple EXE files are not permitted.
    - name: SAP Patching - Web Dispatcher - Prepare - Get the highest version of web dispatcher SAR file
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_sar: >-
          {{
            __sap_patching_register_webdisp_source_dir_content.files
            | map(attribute='path')
            | map('basename')
            | list
            | sort
            | last
          }}

    - name: SAP Patching - Web Dispatcher - Prepare - Check availability of SAPCAR executable
      ansible.builtin.stat:
        path: "{{ __sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}"
      register: __sap_patching_register_sapcar_file_name_stat
      failed_when: not __sap_patching_register_sapcar_file_name_stat.stat.exists


    # Default 'TMP' is used only for folder creation.
    - name: SAP Patching - Web Dispatcher - Prepare - Extract the web dispatcher version from SAR file name
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_pn:
          "{{ (__sap_patching_fact_webdisp_sar
            | regex_search('(?i)SAPWEBDISP_SP_(\\d+)-\\d+.SAR', '\\1')
            | list
            | last) | d('TMP') }}"

    - name: SAP Patching - Web Dispatcher - Prepare - Set fact with extracted web dispatcher directory
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_extract_target:
          "{{ __sap_patching_webdisp_base }}/{{ __sap_patching_webdisp_extracted }}_{{ __sap_patching_fact_webdisp_pn }}"


    - name: SAP Patching - Web Dispatcher - Prepare - Create target web dispatcher directory
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}"
        state: directory
        mode: '0755'
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"


    # Copy only latest SAR file we identified, because Web Dispatcher comes as one SAR file.
    # Moving all files from source could lead to contamination of extracted files.
    - name: SAP Patching - Web Dispatcher - Prepare - Copy identified SAR file to target base
      ansible.builtin.copy:
        src: "{{ sap_patching_webdisp_source }}/{{ __sap_patching_fact_webdisp_sar }}"
        dest: "{{ __sap_patching_webdisp_base }}/{{ __sap_patching_fact_webdisp_sar }}"
        remote_src: true
        mode: 'preserve'
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      when: __sap_patching_webdisp_base != sap_patching_webdisp_source


    - name: SAP Patching - Web Dispatcher - Prepare - Extract web dispatcher SAR file to the target
      ansible.builtin.command:
        cmd: >-
          {{ __sap_patching_sapcar_path }}/{{ sap_patching_sapcar_file_name }}
          -xvf {{ __sap_patching_webdisp_base }}/{{ __sap_patching_fact_webdisp_sar }}
          -R "{{ __sap_patching_fact_webdisp_extract_target }}"
          -manifest SIGNATURE.SMF
      args:
        chdir: "{{ __sap_patching_fact_webdisp_extract_target }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"
      register: __sap_patching_register_extract_result
      changed_when: "'SAPCAR: processing archive' in __sap_patching_register_extract_result.stdout"
      failed_when: __sap_patching_register_extract_result.rc != 0


    - name: SAP Patching - Web Dispatcher - Prepare - Check that web dispatcher extracted path exists
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp"
      register: __sap_patching_register_webdisp_extracted_stat

    - name: SAP Patching - Web Dispatcher - Prepare - Assert web dispatcher extracted path exists
      ansible.builtin.assert:
        that:
          - __sap_patching_register_webdisp_extracted_stat.stat.exists
          - __sap_patching_register_webdisp_extracted_stat.stat.isreg
        fail_msg: |
          FAIL: Expected Web Dispatcher directory '{{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp' does not exist.
          Please check if the SAR file '{{ __sap_patching_fact_webdisp_sar }}' is correct and contains the expected 'sapwebdisp' executable.


    # Reason for noqa: Shell retains the environment variables.
    - name: SAP Patching - Web Dispatcher - Prepare - Check webdisp release and patch number  # noqa command-instead-of-shell
      ansible.builtin.shell:
        cmd: "{{ __sap_patching_fact_webdisp_extract_target }}/sapwebdisp -v"
      environment:
        LD_LIBRARY_PATH: "{{ __sap_patching_fact_webdisp_extract_target }}"
      register: __sap_patching_register_webdisp_release_patch_output
      changed_when: false
      failed_when: __sap_patching_register_webdisp_release_patch_output.rc != 0

    # webdisp is using = between release/patch and the number unlike disp+work which is using just spaces
    - name: SAP Patching - Web Dispatcher - Prepare - Extract webdisp release and patch number from sapwebdisp output
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_release_wd:
          "{{ __sap_patching_register_webdisp_release_patch_output.stdout_lines
            | select('search', '^kernel release') | list | first
            | regex_search('kernel release\\s+=+\\s+(\\d+)', '\\1') | first }}"
        __sap_patching_fact_webdisp_patch_wd:
          "{{ __sap_patching_register_webdisp_release_patch_output.stdout_lines
            | select('search', '^patch number') | list | first
            | regex_search('patch number\\s+=+\\s+(\\d+)', '\\1') | first }}"

    - name: SAP Patching - Web Dispatcher - Prepare - Assert expected webdisp patch number matches extracted SAR patch number
      ansible.builtin.assert:
        that:
          - (__sap_patching_fact_webdisp_patch_wd | int) == (__sap_patching_fact_webdisp_pn | int)
        fail_msg: |
          FAIL: Mismatch between webdisp patch number extracted from sapwebdisp and expected patch number from SAR file names.
          File name patch number: {{ __sap_patching_fact_webdisp_pn }}
          Webdisp patch number: {{ __sap_patching_fact_webdisp_patch_wd }}


    # We copy first, then remove, because Ansible does not have builtin move module.
    - name: SAP Patching - Web Dispatcher - Prepare - Copy temporary web dispatcher directory contents to final destination
      ansible.builtin.copy:
        src: "{{ __sap_patching_fact_webdisp_extract_target }}/"
        dest: "{{ __sap_patching_webdisp_base }}/{{ __sap_patching_webdisp_extracted }}_{{
          __sap_patching_fact_webdisp_release_wd }}p{{ __sap_patching_fact_webdisp_pn }}/"
        remote_src: true
        mode: '0755'
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"

    - name: SAP Patching - Web Dispatcher - Prepare - Remove the temporary web dispatcher directory
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}"
        state: absent

    - name: SAP Patching - Web Dispatcher - Prepare - Update target webdisp SP directory variable after rename - autodetect mode
      ansible.builtin.set_fact:
        __sap_patching_fact_webdisp_extract_target:
          "{{ __sap_patching_webdisp_base }}/{{ __sap_patching_webdisp_extracted }}_{{
            __sap_patching_fact_webdisp_release_wd }}p{{ __sap_patching_fact_webdisp_pn }}"


    - name: SAP Patching - Web Dispatcher - Prepare - Ensure symbolic link for web dispatcher directory is correct
      ansible.builtin.file:
        src: "{{ __sap_patching_fact_webdisp_extract_target }}"
        dest: "{{ __sap_patching_webdisp_base }}/{{ sap_patching_webdisp_to_apply_symlink }}"
        state: link
        force: true
        owner: "{{ sap_patching_file_owner }}"
        group: "{{ sap_patching_file_group }}"
      become: true
      become_user: "{{ sap_patching_file_owner }}"

    - name: SAP Patching - Web Dispatcher - Prepare - Set sap_patching_webdisp_to_apply variable for use in later tasks
      ansible.builtin.set_fact:
        sap_patching_webdisp_to_apply: "{{ __sap_patching_fact_webdisp_extract_target }}"


  # Cleanup all folders created during web dispatcher preparation in case of failure to avoid leaving the system in an inconsistent state.
  rescue:
    - name: SAP Patching - Web Dispatcher - Prepare - Cleanup - Remove target web dispatcher directory in case of failure
      ansible.builtin.file:
        path: "{{ __sap_patching_fact_webdisp_extract_target }}"
        state: absent

    - name: SAP Patching - Web Dispatcher - Prepare - Preparation tasks have failed
      ansible.builtin.fail:
        msg: |
          Web Dispatcher preparation tasks have failed. All created folders during web dispatcher preparation have been removed.
          Please review the error messages above to identify the root cause of the failure and re-run the playbook after resolving the issue.


- name: SAP Patching - Web Dispatcher - Prepare - Inform that SAR files were not found
  ansible.builtin.debug:
    msg: |
      No web dispatcher SAR files found in source directory {{ __sap_patching_webdisp_source }}.
      Skipping web dispatcher preparation.
  when: __sap_patching_register_webdisp_source_dir_content.matched == 0
