# SPDX-License-Identifier: Apache-2.0
---

# Update internal variables as xnw_kernel_restart is shared with kernel.
- name: SAP Patching - Web Dispatcher - Restart - Set fact with tasks specific variables
  ansible.builtin.set_fact:
    __sap_patching_fact_sap_system_sid: "{{ sap_patching_wdp_system_sid | upper }}"
    __sap_patching_fact_sidadm_user: "{{ sap_patching_wdp_system_sid | lower }}adm"
    __sap_patching_fact_kernel_restart_strategy: "all"
    __sap_patching_fact_kernel_or_webdisp: "webdisp"

- name: SAP Patching - Web Dispatcher - Restart - Execute kernel restart function to restart web disp
  ansible.builtin.include_tasks:
    file: xnw_kernel_restart.yml
