# SPDX-License-Identifier: Apache-2.0
---

# # Update variables to pass into shared tasks.
# - name: SAP Patching - Web Dispatcher - Apply - Set fact with 'webdisp' specific variables
#   ansible.builtin.set_fact:
#     __sap_patching_fact_sap_system_sid: "{{ sap_patching_wdp_system_sid | upper }}"
#     __sap_patching_fact_sidadm_user: "{{ sap_patching_wdp_system_sid | lower }}adm"
#     __sap_patching_fact_kernel_to_apply: "{{ sap_patching_webdisp_to_apply | d('') }}"
#     __sap_patching_fact_kernel_to_apply_symlink: "{{ sap_patching_webdisp_to_apply_symlink }}"
#     __sap_patching_fact_kernel_base: "{{ sap_patching_webdisp_base }}"
#     __sap_patching_fact_kernel_files_shared: "{{ sap_patching_webdisp_files_shared | d(true) }}"
#     __sap_patching_fact_kernel_type: "webdisp"

- name: SAP Patching - Web Dispatcher - Apply - Execute shared tasks for kernel apply
  ansible.builtin.include_tasks:
    file: shared_kernel_apply.yml
  vars:
    __sap_patching_fact_sap_system_sid: "{{ sap_patching_wdp_system_sid | upper }}"
    __sap_patching_fact_sidadm_user: "{{ sap_patching_wdp_system_sid | lower }}adm"
    __sap_patching_fact_kernel_base: "{{ sap_patching_webdisp_base }}"
    __sap_patching_fact_kernel_files_shared: "{{ sap_patching_webdisp_files_shared | d(true) }}"
    __sap_patching_fact_kernel_type: "webdisp"
    # Temporary assignments for passing prepared facts from prepare tasks without affecting user variables.
    __sap_patching_fact_kernel_to_apply_user: "{{ sap_patching_webdisp_to_apply | d('') }}"
    __sap_patching_fact_kernel_to_apply_prepare: "{{ __sap_patching_fact_webdisp_to_apply | d('') }}"
    __sap_patching_fact_kernel_to_apply_symlink_user: "{{ sap_patching_webdisp_to_apply_symlink }}"
