---
- name: Inject webdisp variables to reuse kernel_apply task
  ansible.builtin.set_fact:
    _sap_patching_sap_system_sid: "{{ sap_patching_wdp_system_sid }}"
    _sap_patching_kernel_to_apply: "{{ sap_patching_webdisp_to_apply | d() }}"
    _sap_patching_kernel_to_apply_symlink: "{{ sap_patching_webdisp_to_apply_symlink }}"
    _sap_patching_kernel_base: "{{ sap_patching_webdisp_base }}"
    _sap_patching_kernel_extracted_shared: "{{ sap_patching_webdisp_extracted_shared }}"
    _sap_patching_kernel_or_webdisp: "webdisp"

- name: Execute kernel apply function to apply web disp patch
  ansible.builtin.include_tasks:
    file: xnw_kernel_apply.yml
