---
- name: Setting correct variables for restart task
  ansible.builtin.set_fact:
    __sap_patching_fact_sap_system_sid: "{{ sap_patching_wdp_system_sid }}"
    __sap_patching_fact_kernel_restart_strategy: "all"
    __sap_patching_fact_kernel_or_webdisp: "webdisp"

- name: Execute kernel restart function to restart web disp
  ansible.builtin.include_tasks:
    file: xnw_kernel_restart.yml
