---
# RKS documentation - https://help.sap.com/docs/ABAP_PLATFORM_NEW/1ba3197c1aa7489882770103e3a610dc/4036870ddc184419825923abe605e410.html?locale=en-US
# RKS main note - https://me.sap.com/notes/953653
# RKS background processing -https://me.sap.com/notes/1871817
# RKS with HA - https://me.sap.com/notes/2077934

- name: Check sap_patching_kernel_restart_strategy for valid setting
  ansible.builtin.fail:
    msg: "sap_patching_kernel_restart_strategy must be one of: none, all, rks"
  when: __sap_patching_fact_kernel_restart_strategy not in ['bootstrap', 'all', 'rks']


- name: Get a list of sapstartsrv instances
  ansible.builtin.include_tasks:
    file: ../startstop/sapstartsrv_instances.yml

- name: Proceed only if at least one instance is found
  when: __sap_patching_fact_instance_list | d([]) | length > 0
  block:

    # Handle sapuxuserchk manually just before patching as sapcpe can't deal with files owned by root and s-uid set
    # This will ignore HANA's sapuxuserchk as it's stored in /hana/shared and find doesn't follow /usr/sap/SID symlinks (intended behaviour)
    #    find /usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }} -name "sapuxuserchk" -exec chown {{ __sap_patching_fact_sap_system_sid | lower }}adm:sapsys {} \;
    - name: Update sapuxuserchk manually
      ansible.builtin.shell: >-
        find /usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}
        -name "sapuxuserchk" \( -exec cp /usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/SYS/exe/run/sapuxuserchk {} \;
        -false -o -exec chown root:sapsys {} \; -false -o -exec chmod 4755 {} \; \)
      register: __sap_patching_register_sapuxuserchk_chown
      changed_when: __sap_patching_register_sapuxuserchk_chown.rc == 0
      failed_when: __sap_patching_register_sapuxuserchk_chown.rc != 0

    - name: Restart ABAP system using Rolling Kernel Switch (RKS)
      when:
        - __sap_patching_fact_kernel_restart_strategy == 'rks'
        #- "'nwas_abap_ascs' in group_names"
      block:

        - name: Executing RKS check tasks
          ansible.builtin.include_tasks:
            file: xnw_kernel_rks_check.yml
          loop: "{{ __sap_patching_fact_instance_list }}"
          loop_control:
            loop_var: __sap_patching_instance_check
            label: "{{ __sap_patching_instance_check[0] }}{{ __sap_patching_instance_check[1] }}"

        - name: Initiate RKS - one host only (general/non-HA)
          run_once: true
          ansible.builtin.shell: |
            source ~/.profile &&
            sapcontrol -nr {{ __sap_patching_fact_instance_list[0][1] }}
            -function UpdateSystem {{ sap_patching_rks_wait_timeout }} {{ sap_patching_rks_soft_timeout }}
          args:
            executable: /bin/bash
          become: true
          become_user: "{{ __sap_patching_fact_sap_system_sid | lower }}adm"
          register: __sap_patching_register_rks_start
          failed_when:
            - "'HA Product detected' not in __sap_patching_register_rks_start.stdout"
            - "__sap_patching_register_rks_start.rc != 0 or 'FAIL' in __sap_patching_register_rks_start.stdout"
          changed_when: __sap_patching_register_rks_start.rc == 0

        - name: Initiate RKS - one host only (HA)
          when:
            - "'HA Product detected' in __sap_patching_register_rks_start.stdout"
            - "__sap_patching_register_rks_start.rc != 0 or 'FAIL' in __sap_patching_register_rks_start.stdout"
          run_once: true
          ansible.builtin.shell: |
            source ~/.profile &&
            sapcontrol -nr {{ __sap_patching_fact_instance_list[0][1] }}
            -function UpdateSystem {{ sap_patching_rks_wait_timeout }} {{ sap_patching_rks_soft_timeout }} 1
          args:
            executable: /bin/bash
          become: true
          become_user: "{{ __sap_patching_fact_sap_system_sid | lower }}adm"
          register: __sap_patching_register_rks_start2
          failed_when: "__sap_patching_register_rks_start2.rc != 0 or 'FAIL' in __sap_patching_register_rks_start2.stdout"
          changed_when: __sap_patching_register_rks_start2.rc == 0

        - name: Make sure you run {{ __sap_patching_fact_kernel_or_webdisp }}_saproot.yml AFTER all instances have been restarted
          ansible.builtin.fail:
            msg: "You must run {{ __sap_patching_fact_kernel_or_webdisp }}_saproot.yml manually after all instances have been restarted"
          ignore_errors: yes

    - name: Restart/Bootstrap ABAP system and execute saproot.sh
      when:
        - __sap_patching_fact_kernel_restart_strategy == 'all' or __sap_patching_fact_kernel_restart_strategy == "bootstrap"
        - __sap_patching_fact_instance_list | length > 0
        #- group_names | select('search', '^nwas_abap.*') | list | length > 0
      block:

        - name: Stop ABAP system
          # when: __sap_patching_fact_kernel_restart_strategy != "bootstrap"
          ansible.builtin.include_tasks:
            file: ../startstop/abap_stop.yml

        # Now restart the sapstartsrv for each instance found
        - name: Bootstrap each instance in __sap_patching_fact_instance_list
          ansible.builtin.shell: |
            source ~/.profile && sapcontrol -nr {{ item[1] }} -function Bootstrap
          args:
            executable: /bin/bash
          become: true
          become_user: "{{ __sap_patching_fact_sap_system_sid | lower }}adm"
          register: __sap_patching_register_sssrv_restart
          failed_when: "__sap_patching_register_sssrv_restart.rc != 0 or 'FAIL' in __sap_patching_register_sssrv_restart.stdout"
          changed_when: __sap_patching_register_sssrv_restart.rc == 0
          loop: "{{ __sap_patching_fact_instance_list }}"

        # This is a stupid way of doing it, but we need to wait until all sapstartsrv have been restarted
        - name: Wait for 1 minute after bootstrap
          #when: "'nwas_abap_ascs' in group_names"
          ansible.builtin.wait_for:
            timeout: 60
            #timeout: 5   #CHANGE ME TO 60

        - name: Execute saproot.sh to adjust permissions after patching
          ansible.builtin.include_tasks: "nw/{{ __sap_patching_fact_kernel_or_webdisp }}_saproot.yml"

        - name: Start ABAP system
          when: __sap_patching_fact_kernel_restart_strategy != "bootstrap"
          ansible.builtin.include_tasks:
            file: ../startstop/abap_start.yml
