---
- name: Check if saproot.sh exists and is executable
  ansible.builtin.stat:
    path: /usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/SYS/exe/run/saproot.sh
  register: __sap_patching_register_kernel_saproot_sh_stat

- name: Execute saproot.sh to adjust permissions after patching
  become: true
  when: __sap_patching_register_kernel_saproot_sh_stat.stat.exists and __sap_patching_register_kernel_saproot_sh_stat.stat.mode is search('..7$|..5$|..1$')
  ansible.builtin.shell: |
    /usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/SYS/exe/run/saproot.sh {{ __sap_patching_fact_sap_system_sid | upper }}
  register: __sap_patching_register_kernel_saproot
  changed_when: __sap_patching_register_kernel_saproot.rc == 0
  failed_when: __sap_patching_register_kernel_saproot.rc != 0
