---
# Sanitation and checks
- name: Set {{ __sap_patching_fact_kernel_to_apply }} to default if not defined or empty
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_to_apply_symlink }}"
  when: __sap_patching_fact_kernel_to_apply is not defined or __sap_patching_fact_kernel_to_apply | type_debug == "NoneType" or __sap_patching_fact_kernel_to_apply | d('',true) |  length == 0

- name: Prepend __sap_patching_fact_kernel_base if __sap_patching_fact_kernel_to_apply is not an absolute path
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_base }}/{{ __sap_patching_fact_kernel_to_apply }}"
  when:
    - __sap_patching_fact_kernel_to_apply is defined
    - not __sap_patching_fact_kernel_to_apply.startswith('/')

# - name: Append __sap_patching_kernel_extracted to sap_patching_kernel_to_apply if not present
#   ansible.builtin.set_fact:
#     __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_to_apply }}/{{ __sap_patching_kernel_extracted }}"
#   when:
#     - __sap_patching_fact_kernel_to_apply is defined
#     - __sap_patching_fact_kernel_or_webdisp == "abap_kernel"
#     - not __sap_patching_fact_kernel_to_apply | regex_search('(^|/)' ~ __sap_patching_kernel_extracted ~ '(/|$)')

# Execute these checks only if the files to be applied are on shared folder directly accessible from the sap host
- name: Execute checks of the {{ __sap_patching_fact_kernel_or_webdisp }} files which will be applied in a moment
  when: "__sap_patching_fact_kernel_extracted_shared | bool"
  block:
    - name: Check that {{ __sap_patching_fact_kernel_to_apply }} exists
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_kernel_to_apply }}"
      register: __sap_patching_register_kernel_to_apply_stat
      failed_when: not __sap_patching_register_kernel_to_apply_stat.stat.exists
      changed_when: false

    - name: Ensure {{ __sap_patching_fact_kernel_to_apply }} is a directory or symlink
      ansible.builtin.assert:
        that:
          - __sap_patching_register_kernel_to_apply_stat.stat.isdir or __sap_patching_register_kernel_to_apply_stat.stat.islnk
        fail_msg: "{{ __sap_patching_fact_kernel_to_apply }} is not a directory or symlink"
        success_msg: "{{ __sap_patching_fact_kernel_to_apply }} is a directory or symlink"
      changed_when: false

    - name: Check the content of {{ __sap_patching_fact_kernel_to_apply }}
      ansible.builtin.find:
        paths: "{{ __sap_patching_fact_kernel_to_apply }}"
        file_type: file
      register: __sap_patching_register_kernel_to_apply_files
      changed_when: false

    - name: Ensure {{ __sap_patching_fact_kernel_to_apply }} is not empty
      ansible.builtin.assert:
        that:
          - __sap_patching_register_kernel_to_apply_files.matched | int > 0
        fail_msg: "{{ __sap_patching_fact_kernel_to_apply }} is empty, this is unexpected for correctly extracted kernel source"
        success_msg: "{{ __sap_patching_fact_kernel_to_apply }} is not empty"
      changed_when: false

- name: Set global exe Directory
  ansible.builtin.set_fact:
    sap_patching_kernel_global_exe: "/usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/SYS/exe/run"
  when:
    - sap_patching_kernel_global_exe is not defined or sap_patching_kernel_global_exe | d('', true) | length == 0

- name: Check that {{ sap_patching_kernel_global_exe }} exists
  ansible.builtin.stat:
    path: "{{ sap_patching_kernel_global_exe }}"
  register: __sap_patching_register_sapmnt_exe_stat
  changed_when: false

- name: Continue if the target directory is present (this will silently skip servers without kernel/webdisp present)
  when:
    - __sap_patching_register_sapmnt_exe_stat.stat.exists
    - __sap_patching_register_sapmnt_exe_stat.stat.islnk or __sap_patching_register_sapmnt_exe_stat.stat.isdir
  block:

# Changed asswert/fail to skip, keeping this for reference until the end of 2027
# - name: Ensure {{ sap_patching_kernel_global_exe }} is a directory or a link
#   ansible.builtin.assert:
#     that:
#       - __sap_patching_register_sapmnt_exe_stat.stat.exists
#       - __sap_patching_register_sapmnt_exe_stat.stat.islnk or __sap_patching_register_sapmnt_exe_stat.stat.isdir
#     fail_msg: "{{ sap_patching_kernel_global_exe }} does not exist or is not a symlink/directory"
#     success_msg: "{{ sap_patching_kernel_global_exe }} exists and is a symlink/directory"
#   changed_when: false

    - name: Check the content of {{ sap_patching_kernel_global_exe }}
      ansible.builtin.find:
        paths: "{{ sap_patching_kernel_global_exe }}"
        file_type: file
      register: __sap_patching_register_sapmnt_exe_files
      changed_when: false

    - name: Ensure {{ sap_patching_kernel_global_exe }} is not empty
      ansible.builtin.assert:
        that:
          - __sap_patching_register_sapmnt_exe_files.matched | int > 0
        fail_msg: "{{ sap_patching_kernel_global_exe }} is empty, this is unexpected for a correctly installed system"
        success_msg: "{{ sap_patching_kernel_global_exe }} is not empty"
      changed_when: false

    # Execution
    - name: Copy kernel files to global exe directory
      ansible.builtin.copy:
        src: "{{ __sap_patching_fact_kernel_to_apply }}/"
        dest: "{{ sap_patching_kernel_global_exe }}"
        remote_src: "{{ __sap_patching_fact_kernel_extracted_shared | bool }}"
        owner: "{{ __sap_patching_fact_sap_system_sid | lower }}adm"
        group: sapsys
        mode: '0755'
        directory_mode: '0755'
      changed_when: true
