# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Patching - Kernel - Apply - Set fact with kernel symlink if kernel is not specified
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_to_apply_symlink }}"
  when:
    - __sap_patching_fact_kernel_to_apply is not defined
      or __sap_patching_fact_kernel_to_apply | type_debug == "NoneType"
      or __sap_patching_fact_kernel_to_apply | string | trim | length == 0

- name: SAP Patching - Kernel - Apply - Update kernel path if it is not an absolute path
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_base }}/{{ __sap_patching_fact_kernel_to_apply }}"
  when: not __sap_patching_fact_kernel_to_apply.startswith('/')

# - name: Append __sap_patching_kernel_extracted to sap_patching_kernel_to_apply if not present
#   ansible.builtin.set_fact:
#     __sap_patching_fact_kernel_to_apply: "{{ __sap_patching_fact_kernel_to_apply }}/{{ __sap_patching_kernel_extracted }}"
#   when:
#     - __sap_patching_fact_kernel_to_apply is defined
#     - __sap_patching_fact_kernel_or_webdisp == "abap_kernel"
#     - not __sap_patching_fact_kernel_to_apply | regex_search('(^|/)' ~ __sap_patching_kernel_extracted ~ '(/|$)')


# Execute these checks only if the files to be applied are on shared folder directly accessible from the sap host
- name: Block for kernel files on shared storage
  when: __sap_patching_fact_kernel_extracted_shared
  block:
    - name: SAP Patching - Kernel - Apply - Check availability of kernel source directory
      ansible.builtin.stat:
        path: "{{ __sap_patching_fact_kernel_to_apply }}"
      register: __sap_patching_register_kernel_to_apply_stat
      failed_when: not __sap_patching_register_kernel_to_apply_stat.stat.exists

    - name: SAP Patching - Kernel - Apply - Assert that it is a directory or symlink
      ansible.builtin.assert:
        that:
          - __sap_patching_register_kernel_to_apply_stat.stat.isdir
            or __sap_patching_register_kernel_to_apply_stat.stat.islnk
        fail_msg: |
          FAIL: The directory "{{ __sap_patching_fact_kernel_to_apply }}" is not a directory or symlink.

    - name: SAP Patching - Kernel - Apply - Check the content of '{{ __sap_patching_fact_kernel_to_apply }}'
      ansible.builtin.find:
        paths: "{{ __sap_patching_fact_kernel_to_apply }}"
        file_type: file
      register: __sap_patching_register_kernel_to_apply_files

    - name: SAP Patching - Kernel - Apply - Assert that '{{ __sap_patching_fact_kernel_to_apply }}' is not empty
      ansible.builtin.assert:
        that:
          - __sap_patching_register_kernel_to_apply_files.matched | int > 0
        fail_msg: |
          FAIL: The directory "{{ __sap_patching_fact_kernel_to_apply }}" is empty and patching cannot proceed!
          Ensure that the kernel SAR files have been extracted to the shared folder and re-run the playbook.


- name: SAP Patching - Kernel - Apply - Set fact with global exe directory
  ansible.builtin.set_fact:
    __sap_patching_fact_kernel_global_exe:
      "/usr/sap/{{ __sap_patching_fact_sap_system_sid | upper }}/SYS/exe/run"

- name: SAP Patching - Kernel - Apply - Check availability of {{ __sap_patching_fact_kernel_global_exe }}
  ansible.builtin.stat:
    path: "{{ __sap_patching_fact_kernel_global_exe }}"
  register: __sap_patching_register_sapmnt_exe_stat


# Continue if the target directory is present (this will silently skip servers without kernel/webdisp present)
- name: Block for kernel apply execution when global exe directory is present
  when:
    - __sap_patching_register_sapmnt_exe_stat.stat.exists
    - __sap_patching_register_sapmnt_exe_stat.stat.islnk
      or __sap_patching_register_sapmnt_exe_stat.stat.isdir
  block:

    - name: SAP Patching - Kernel - Apply - Check the content of {{ __sap_patching_fact_kernel_global_exe }}
      ansible.builtin.find:
        paths: "{{ __sap_patching_fact_kernel_global_exe }}"
        file_type: file
      register: __sap_patching_register_sapmnt_exe_files

    - name: SAP Patching - Kernel - Apply - Assert that global exe directory is not empty
      ansible.builtin.assert:
        that:
          - __sap_patching_register_sapmnt_exe_files.matched | int > 0
        fail_msg: |
          FAIL: The global exe directory "{{ __sap_patching_fact_kernel_global_exe }}" is empty and patching cannot proceed!
          Ensure that targeted SAP system is correctly installed.

    - name: SAP Patching - Kernel - Apply - Copy kernel files to global exe directory
      ansible.builtin.copy:
        src: "{{ __sap_patching_fact_kernel_to_apply }}/"
        dest: "{{ __sap_patching_fact_kernel_global_exe }}"
        # TODO: Review concept behind what means shared.
        remote_src: "{{ __sap_patching_fact_kernel_extracted_shared | bool }}"
        owner: "{{ __sap_patching_fact_sap_system_sid | lower }}adm"
        group: sapsys
        mode: '0755'
        directory_mode: '0755'
      changed_when: true

  # This rescue block cannot remove any files in current form, because backup is not implemented.
  # TODO: Add global exe backup tasks that can be used in rescue block to restore original state.
  rescue:
    - name: SAP Patching - Kernel - Apply - Kernel patching tasks have failed
      ansible.builtin.fail:
        msg: |
          Kernel patching tasks have failed.
          Please review the error messages above to identify the root cause of the failure and re-run the playbook after resolving the issue.
