# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Patching - Executing step {{ __sap_patching_step }}
  ansible.builtin.include_tasks:
    file: "{{ __sap_patching_exec_def[__sap_patching_step].file }}"
  run_once: "{{ __sap_patching_exec_def[__sap_patching_step].run_once | d(false) }}"
  vars:
    __sap_patching_params: "{{ __sap_patching_exec_def[__sap_patching_step].vars | d({}) }}"
  tags:
    - always
