---
#### Validate required variables ####
- name: Validate mandatory variables
  ansible.builtin.include_tasks:
    file: validations/main.yml

- name: Execute validator for each step in the execution plan
  ansible.builtin.include_tasks:
    file: validator.yml
  loop: "{{ sap_patching_execution_plan }}"
  loop_control:
    label: "Checking step: {{ item }}"

# - name: Looping through the execution plan
#   debug:
#     msg:
#       - "Executing step: {{ item }}"
#       - "{{ __sap_patching_exec_def[item].file }}"
#       - "{{ __sap_patching_exec_def[item].tags }}"
#       - "{{ __sap_patching_exec_def[item].where }}"
#   loop: "{{ sap_patching_execution_plan }}"
#   loop_control:
#     label: "Executing step: {{ item }}"
#   when: "__sap_patching_exec_def[item].where | from_yaml"

- name: Looping through the execution plan
  ansible.builtin.include_tasks:
    file: main_loop.yml
  loop: "{{ sap_patching_execution_plan }}"
  loop_control:
    loop_var: __sap_patching_step
    label: "Executing step: {{ __sap_patching_step }}"
  # when: "__sap_patching_exec_def[__sap_patching_step].where | from_yaml"
